"use client";

import { useRef, useState } from "react";
import type { ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import {
  Activity, Award, ArrowLeft, ArrowRight, BarChart3, BookOpen, Bot, CalendarDays, Check, ChevronDown, ChevronRight, CircleAlert, CircleCheck, Clock3, Download, EyeOff, FileDown, FileText, Flame, Gauge, Image, Info, Link2, List, LockKeyhole, MessageCircle, Mic2, Moon, Network, Paperclip, RefreshCw, Send, Share2, ShieldCheck, Smile, Search, Sparkles, Target, Timer, TrendingUp, UploadCloud, UserRound, Users, Video, X, Zap,
} from "lucide-react";
import { analyzeChat, formatMinutesForReport, PERIODS } from "@/lib/chat/analyzers";
import { ChatParseError, parseChatFile, platformLabels } from "@/lib/chat/parsers";
import type { AiAnalysis, AnalysisReport, NormalizedMessage, ParseResult, Platform } from "@/lib/chat/types";
import { Achievements, AskAi, Balance, ConversationDrive, EmotionTrend, HeatmapV2, Highlights, Links, MemorySearch, Quality, Rhythm, Silence, Similarity, TopicLifecycle } from "./v2-sections";
import { useGsapMotion } from "./use-gsap-motion";

type FlowStep = "home" | "platform" | "guide" | "upload" | "identify" | "report";
type RangePreset = "all" | "thisYear" | "lastYear" | "last12" | "custom";
type AnalysisRange = { preset: RangePreset; start?: string; end?: string };
type ShareMode = "full" | "recap" | "achievements";
type TabId = "overview" | "interaction" | "response" | "habits" | "words" | "personality" | "topics" | "conflict" | "timeline" | "recap" | "ai" | "emotion" | "heatmap" | "drive" | "rhythm" | "similarity" | "lifecycle" | "silence" | "links" | "balance" | "achievements" | "highlights" | "search" | "quality";

type PlatformMeta = { label: string; icon: string; description: string; color: string; steps: { title: string; body: string }[]; formats: string; device: string; filePath: string; preparation: string[]; checks: string[]; pitfalls: string[]; officialUrl: string };
const PLATFORM_META: Record<Platform, PlatformMeta> = {
  line: { label: "LINE", icon: "LINE", description: "支援常見的 LINE 純文字聊天匯出。", color: "logo-line", formats: ".txt（LINE 聊天記錄）", device: "LINE 手機版或 Windows / Mac 電腦版", filePath: "手機分享後的 .txt 檔，或電腦版儲存的聊天文字檔", preparation: ["請先在 LINE 開啟你與另一位對象的一對一聊天室。", "確認 LINE 已更新到近期版本，並準備好把檔案傳到目前使用的手機或電腦。", "如果你要保留聊天在 LINE 裡，請另外使用 LINE 的備份功能；文字匯出檔只能用來閱讀與分析，不能還原聊天。"], steps: [{ title: "開啟目標聊天室的設定", body: "在 LINE 手機版進入目標聊天室，點擊上方的選單或聊天室名稱，再進入「設定」。在 Windows / Mac 版則開啟該聊天室，點擊上方選單。" }, { title: "選擇匯出聊天記錄", body: "手機版選擇「傳送聊天記錄」或「Export chat history」；電腦版可選擇「儲存聊天」或「Save chat」。介面名稱可能因作業系統、版本與語言不同而略有差異。" }, { title: "把文字檔存到容易找到的位置", body: "手機版可以使用檔案、雲端硬碟、AirDrop 或寄給自己；電腦版直接儲存到桌面或下載資料夾。請確認最後產生的是 .txt，而不是截圖或 LINE 備份檔。" }, { title: "回到這裡上傳", body: "選擇剛剛的 .txt 檔案。檔案會先留在瀏覽器中解析，不會自動上傳；成功後我們會先顯示辨識到的兩位聊天者，讓你確認哪一位是你。" }], checks: ["用文字編輯器打開檔案，確認看得到日期、時間、發送者與內容。", "確認檔案不是空白、截圖、ZIP 或 LINE 的雲端備份檔。", "若只看到很短的一段，可能是電腦版只保存當下已載入的訊息；請先在聊天室往上載入更多內容，再重新儲存。"], pitfalls: ["LINE 的文字匯出通常不包含圖片、影片原始內容；這些媒體可能不會出現在 .txt 中。", "官方說明指出，文字檔備份不能拿來還原 LINE 聊天；這個檔案只提供本工具分析。", "不要上傳整個 LINE 資料夾，也不要把備份密碼或帳號資料放在檔案裡。"], officialUrl: "https://help.line.me/line/smartphone/sp?contentId=20007388&lang=en" },
  instagram: { label: "Instagram", icon: "◎", description: "支援 Meta 帳號資料下載中的訊息 JSON。", color: "logo-instagram", formats: ".json、部分 .html", device: "手機或電腦瀏覽器的 Meta 帳號中心", filePath: "解壓縮後的 messages / inbox / 對話資料夾內之 message_*.json", preparation: ["請使用你有權查看的 Instagram 帳號，並只下載需要分析的訊息資料。", "建議選 JSON，不建議只下載 HTML；JSON 比較容易保留發送者、時間與文字欄位。", "Meta 可能需要一段時間準備下載檔，請等到收到可下載通知後，再完整下載 ZIP。"], steps: [{ title: "從 Instagram 進入帳號中心", body: "開啟 Instagram 個人檔案 → 右上角選單 →「設定和動態」→「帳號中心」→「你的資訊和權限」。不同版本可能直接顯示「下載你的資訊」。" }, { title: "建立下載要求", body: "選擇「下載或傳輸資訊」，選取你的 Instagram 帳號，再選擇「部分資訊」或只勾選「訊息」。若畫面只有完整下載選項，也請在完成後只挑出目標對話檔。" }, { title: "設定格式與日期範圍", body: "格式請選 JSON；日期範圍可選全部或指定期間，媒體品質不影響本工具的文字統計。確認要求後等待 Meta 準備 ZIP，不要截取畫面當作聊天檔案。" }, { title: "解壓縮並找到單一對話檔", body: "下載 ZIP 並解壓縮，通常可在 messages、inbox 或對話名稱資料夾中找到 message_1.json、message_2.json 等檔案。V1 一次處理一個檔案，請挑選包含完整 messages 陣列的檔案；若 Meta 將對話拆成多段，部分期間可能無法合併。" }, { title: "回到這裡上傳", body: "選擇 JSON 檔案後，系統會在瀏覽器本機讀取 sender_name、timestamp_ms、content 與附件類型。成功後請檢查兩位聊天者與訊息數量是否合理。" }], checks: ["打開 JSON 後，確認內容中可以找到 messages、sender_name 或 sender，以及 timestamp_ms、timestamp 或 date。", "檢查這是不是目標一對一聊天室，而不是整個 inbox 清單或帳號摘要檔。", "如果有 message_1、message_2 等分段檔，先選包含較早或較完整 messages 的檔案，並在報告的資料品質頁查看日期覆蓋率。"], pitfalls: ["Meta 的資料夾名稱、欄位名稱與下載路徑可能因版本、地區與語言不同而改變。", "HTML 只作為相容嘗試，JSON 是推薦格式；若只有附件而沒有文字，文字雲與話題分析會較有限。", "請勿把整個帳號 ZIP 或含有其他人的資料夾直接上傳；先解壓縮並挑選目標對話檔。"], officialUrl: "https://help.instagram.com/181231772500920/" },
  messenger: { label: "Messenger", icon: "✦", description: "支援 Meta 帳號資料下載中的 Messenger 訊息 JSON。", color: "logo-messenger", formats: ".json、部分 .html", device: "Facebook / Messenger 帳號中心，手機或電腦瀏覽器皆可", filePath: "解壓縮後的 messages / inbox / 對話資料夾內之 message_*.json", preparation: ["請先確認你要分析的是私人一對一對話，而不是社團、群組或整個收件匣匯出。", "建議使用 JSON 格式，並將日期範圍縮小到真正需要的期間，降低檔案大小與不必要資料。", "端對端加密聊天室可能有另外的資料下載入口；若匯出結果缺少訊息，請依 Messenger 顯示的說明下載對應資料。"], steps: [{ title: "進入 Facebook 帳號中心", body: "開啟 Facebook → 個人設定 →「帳號中心」→「你的資訊和權限」。也可以從 Messenger 或 Instagram 的帳號中心進入相同功能。" }, { title: "選擇下載你的資訊", body: "點擊「下載或傳輸資訊」，選取 Facebook 帳號，選擇「部分資訊」並勾選「訊息」。若畫面以舊版名稱顯示，可能叫「下載你的資訊」或「存取你的資訊」。" }, { title: "選 JSON 與日期範圍", body: "格式選 JSON，媒體品質可以選低或中，因為 V1 不分析圖片、影片與語音內容。日期範圍可以選指定期間，確認後送出下載要求。" }, { title: "解壓縮 ZIP 並挑出目標聊天", body: "完成下載後解壓縮，進入 messages、inbox 或對話名稱資料夾，尋找 message_1.json 等訊息檔。不要選 index、account 或整個 ZIP；一次上傳一個包含 messages 陣列的對話檔。" }, { title: "回到這裡上傳並核對", body: "上傳 JSON 後，系統會在本機讀取發送者、時間、文字與附件類型。看到兩位聊天者後，先比對訊息數量、日期範圍與對話名稱，再開始分析。" }], checks: ["打開 JSON 後，確認看得到 messages 陣列與 sender_name、timestamp_ms、content 等欄位。", "確認檔案不是 Messenger 的帳號設定、索引、聯絡人或整個收件匣摘要。", "端對端加密或已刪除的訊息可能不在一般下載檔中；資料品質頁會提醒日期間隔與未知訊息。"], pitfalls: ["Facebook / Meta 的設定名稱與下載路徑可能因版本、地區與語言不同而變動。", "若對話被分成多個 message_*.json，目前 V1 一次處理一個檔案，未合併的部分會造成日期覆蓋不足。", "請不要把整個帳號下載 ZIP 上傳；先解壓縮、挑選單一目標對話，避免意外分享其他聊天資料。"], officialUrl: "https://www.facebook.com/help/messenger-app/713635396288741" },
};

const TABS: { id: TabId; label: string; icon: LucideIcon }[] = [
  { id: "overview", label: "總覽", icon: Gauge }, { id: "interaction", label: "互動", icon: Activity }, { id: "response", label: "回覆", icon: Timer }, { id: "habits", label: "聊天習慣", icon: Clock3 }, { id: "emotion", label: "情緒趨勢", icon: Activity }, { id: "heatmap", label: "聊天熱度", icon: Flame }, { id: "drive", label: "聊天帶動力", icon: Zap }, { id: "rhythm", label: "對話節奏", icon: MessageCircle }, { id: "similarity", label: "風格相似", icon: Users }, { id: "words", label: "文字雲", icon: MessageCircle }, { id: "personality", label: "聊天人格", icon: Users }, { id: "topics", label: "話題", icon: List }, { id: "lifecycle", label: "話題生命週期", icon: TrendingUp }, { id: "conflict", label: "衝突與恢復", icon: RefreshCw }, { id: "silence", label: "沉默分析", icon: Moon }, { id: "links", label: "連結分析", icon: Link2 }, { id: "balance", label: "聊天平衡度", icon: Activity }, { id: "timeline", label: "時間軸", icon: Network }, { id: "highlights", label: "聊天亮點", icon: Sparkles }, { id: "achievements", label: "聊天成就", icon: Award }, { id: "recap", label: "年度回顧", icon: Sparkles }, { id: "quality", label: "資料品質", icon: ShieldCheck }, { id: "search", label: "記憶搜尋", icon: Search }, { id: "ai", label: "AI 報告", icon: Bot },
];

const mediaItems = [
  { key: "image", icon: Image, label: "圖片" }, { key: "video", icon: Video, label: "影片" }, { key: "audio", icon: Mic2, label: "語音" }, { key: "sticker", icon: Smile, label: "貼圖" }, { key: "file", icon: Paperclip, label: "檔案" },
] as const;

function Logo({ small = false }: { small?: boolean }) { return <span className="brand-mark"><span className="brand-icon" />{!small && <span>AI Chat Analyzer</span>}</span>; }
function Avatar({ name, color = "blue" }: { name: string; color?: "blue" | "yellow" }) { return <span className={`avatar ${color}`}>{name.slice(0, 1).toUpperCase()}</span>; }
function delay(ms: number) { return new Promise((resolve) => setTimeout(resolve, ms)); }
function prettyCount(value: number) { return value.toLocaleString("zh-TW"); }
function percent(value: number) { return `${Math.round(value)}%`; }
function shortName(name: string) { return name.length > 10 ? `${name.slice(0, 10)}…` : name; }
function maxValue(values: number[]) { return Math.max(1, ...values); }
function levelText(score: number) { return score >= 70 ? "高" : score >= 45 ? "中" : "低"; }
function dateInputValue(value?: string) { return value ? value.slice(0, 10) : ""; }
function filteredByRange(messages: NormalizedMessage[], range: AnalysisRange) {
  if (range.preset === "all") return messages;
  const now = new Date(); let start: Date | undefined; let end: Date | undefined;
  if (range.preset === "thisYear") start = new Date(now.getFullYear(), 0, 1);
  if (range.preset === "lastYear") { start = new Date(now.getFullYear() - 1, 0, 1); end = new Date(now.getFullYear(), 0, 1); }
  if (range.preset === "last12") { start = new Date(now); start.setFullYear(start.getFullYear() - 1); }
  if (range.preset === "custom") { start = range.start ? new Date(`${range.start}T00:00:00`) : undefined; end = range.end ? new Date(`${range.end}T23:59:59`) : undefined; }
  return messages.filter((message) => { const timestamp = Date.parse(message.timestamp); return (!start || timestamp >= start.getTime()) && (!end || timestamp <= end.getTime()); });
}
function rangeLabel(range: AnalysisRange) { return range.preset === "all" ? "全部紀錄" : range.preset === "thisYear" ? "今年" : range.preset === "lastYear" ? "去年" : range.preset === "last12" ? "最近一年" : `${range.start ?? "開始"}–${range.end ?? "現在"}`; }

const FAQ_ITEMS = [
  { question: "上傳聊天檔案後，會被傳到伺服器嗎？", answer: "不會。基本分析的檔案讀取、解析與統計都在你的瀏覽器中完成。原始聊天檔案不會因為選擇檔案就自動送到後端；關閉分頁後，本機分析資料也會被清除。" },
  { question: "目前支援哪些平台與檔案格式？", answer: "V1 支援 LINE、Instagram 與 Facebook Messenger。LINE 主要支援 .txt；Instagram 與 Messenger 主要支援 Meta 資料下載中的 .json，部分 .html 也可以嘗試。不同平台或版本的匯出格式可能不同，請先查看對應教學。" },
  { question: "可以分析群組聊天嗎？", answer: "目前版本主要支援兩人聊天。若偵測到超過兩位聊天者，系統會清楚提示並停止分析，不會把群組對話誤當成兩人關係。多人聊天分析功能正在規劃中。" },
  { question: "主動程度、聊天人格和衝突分析準確嗎？", answer: "這些是根據可觀察聊天行為產生的推測，不是事實判決。系統會參考對話開啟、回覆節奏、上下文與語氣變化，並顯示分析依據與可信度；它不能知道對方真正的想法。" },
  { question: "啟用 AI 深度分析時，會送出哪些資料？", answer: "只有你主動按下同意後才會執行。送出的內容會盡可能去除姓名、電話、Email、地址與原始檔案，只保留必要的統計、主題、回覆節奏、行為標籤與疑似事件摘要。沒有你的同意，不會送出。" },
  { question: "可以下載 PDF 或建立分享連結嗎？", answer: "可以。PDF 由瀏覽器列印功能產生，適合儲存成漂亮的聊天回顧。建立分享報告時，後端只保存匿名化的統計與摘要，不會公開完整聊天內容；分享連結使用不可預測的隨機 ID。" },
];

function FaqItem({ question, answer, open, onToggle }: { question: string; answer: string; open: boolean; onToggle: () => void }) {
  return <div className={`faq-item ${open ? "open" : ""}`}><button className="faq-question" aria-expanded={open} onClick={onToggle}><span>{question}</span><ChevronDown size={17} /></button>{open && <div className="faq-answer"><p>{answer}</p></div>}</div>;
}

function FAQSection() {
  const [openIndex, setOpenIndex] = useState(0);
  return <section className="section section-muted faq-section" id="faq"><div className="page-wrap"><div className="section-heading"><div><span className="eyebrow">Questions, answered</span><h2>常見問題</h2></div><p>第一次使用前想知道的事，都整理在這裡。還有疑問時，也可以回到匯出教學重新確認格式。</p></div><div className="faq-grid">{FAQ_ITEMS.map((item, index) => <FaqItem key={item.question} question={item.question} answer={item.answer} open={openIndex === index} onToggle={() => setOpenIndex(openIndex === index ? -1 : index)} />)}</div><div className="faq-note"><Info size={16} /><span>找不到你的平台？V1 目前專注 LINE、Instagram 與 Messenger，未來會再加入更多匯出格式。</span></div></div></section>;
}

function PrivacyTermsTrigger({ compact = false }: { compact?: boolean }) {
  const [open, setOpen] = useState(false);
  return <><button className={compact ? "nav-link nav-button" : "footer-link"} onClick={() => setOpen(true)}>{compact ? "隱私條款" : "查看隱私條款"}</button>{open && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="privacy-title" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><div className="modal modal-large"><div className="modal-heading"><span className="feature-icon"><ShieldCheck size={19} /></span><div><h3 id="privacy-title">隱私條款與資料使用說明</h3><p>最後更新：2026 年 3 月 · 以透明、最小化為原則</p></div><button className="btn-ghost modal-close" aria-label="關閉隱私條款" onClick={() => setOpen(false)}><X size={16} /></button></div><div className="privacy-content"><section><h4>1. 本機優先分析</h4><p>你選擇的原始聊天檔案會先留在目前裝置的瀏覽器記憶體中，完成檔案讀取、格式解析、訊息統計、Emoji、文字雲與基本互動分析。網站不會因為你按下「選擇檔案」就自動上傳原始聊天內容。</p></section><section><h4>2. AI 深度分析是選用功能</h4><p>只有當你主動選擇「啟用 AI 深度分析」，並按下「我了解，開始 AI 分析」後，必要的去識別化分析摘要才會傳送給 AI 服務。未經同意，AI 不會執行。</p></section><section><h4>3. 資料最小化與去識別化</h4><p>送出 AI 前會優先移除姓名與不必要的個人識別資料，使用 PERSON_A / PERSON_B 等代稱。基本分析不需要帳號、登入或註冊；請你也不要把整個帳號資料夾上傳。</p></section><section><h4>4. 分享報告</h4><p>建立分享報告是另一個需要你主動操作的功能。分享頁只包含統計、圖表、文字雲、聊天人格、年度回顧與 AI 摘要，不包含完整聊天原文。匿名聚合報告會保存在分享服務中，供持有隨機連結的人查看。</p></section><section><h4>5. 保存與你的選擇</h4><p>原始聊天檔案不會被網站保存。關閉分析分頁後，本機工作階段資料會被清除。你可以不啟用 AI、不建立分享報告，仍然使用完整的基本分析與瀏覽器列印功能。</p></section><section><h4>6. 分析限制與免責</h4><p>主動程度、互動投入、疑似衝突、疑似恢復與聊天人格都是從聊天特徵產生的觀察，不是心理診斷，也不是對任何關係的判決。資料缺少聲音、表情、已讀狀態或上下文時，結果可能不完整。</p></section></div><div className="notice" style={{ marginTop: 20 }}><LockKeyhole size={16} style={{ flex: "0 0 auto" }} /><span>使用本工具即表示你了解：基本分析優先在本機進行；任何 AI 或分享資料傳送，都必須經過你的明確操作與同意。</span></div><div className="modal-actions"><button className="btn-primary" onClick={() => setOpen(false)}>我了解，關閉說明</button></div></div></div>}</>;
}

function HomePage({ onStart }: { onStart: () => void }) {
  return <div className="app-shell">
    <header className="page-wrap top-nav"><Logo /><div className="nav-actions"><a className="nav-link" href="#how-it-works">怎麼使用</a><PrivacyTermsTrigger compact /><button className="btn-primary" onClick={onStart}>開始分析 <ArrowRight size={15} /></button></div></header>
    <main>
      <section className="page-wrap hero">
        <div className="reveal reveal-delay-1"><span className="eyebrow">A clearer look at your conversations</span><h1>看看你們的聊天，<em>究竟藏著什麼？</em></h1><p className="hero-copy">匯入聊天紀錄，從訊息、互動、時間與對話脈絡，探索你們的聊天故事。不是測驗，也不是關係判決，只把可觀察的線索整理給你。</p><div className="hero-actions"><button className="btn-primary btn-lg" onClick={onStart}>開始分析 <ArrowRight size={17} /></button><a className="btn-ghost btn-lg" href="#how-it-works">先了解流程</a></div><div className="trust-row"><span><LockKeyhole size={14} />預設在你的裝置上處理</span><span><UserRound size={14} />不需要登入</span><span><Check size={14} />支援三大平台</span></div></div>
        <div className="hero-art reveal reveal-delay-2" aria-label="聊天分析示意圖"><div className="chat-card"><div className="chat-head"><div className="chat-person"><Avatar name="A" /><span>一段聊天紀錄</span></div><span className="chat-date">local analysis</span></div><div className="chat-bubbles"><div className="bubble left">你明天有空嗎？<small>22:14</small></div><div className="bubble right">有呀，怎麼了？<small>22:16 · 回覆很快</small></div><div className="bubble left">想去吃那間新開的店 😂<small>22:17</small></div><div className="bubble right">好啊！我來找時間～<small>22:21</small></div></div><div className="trust-row" style={{ marginTop: 4 }}><span><Activity size={13} />互動節奏</span><span><BarChart3 size={13} />聊天習慣</span></div></div><div className="art-label"><b>✦</b> 從數據讀出聊天故事</div></div>
      </section>
      <section className="section section-muted" id="privacy"><div className="page-wrap"><div className="section-heading"><div><span className="eyebrow">Built around privacy</span><h2>先保護，再分析</h2></div><p>聊天內容是你的。基本分析在瀏覽器完成；只有你主動同意時，才會將必要的去識別化資料送出做 AI 深度分析。</p></div><div className="feature-grid"><Feature icon={ShieldCheck} title="本機優先" text="檔案讀取、解析與統計都在這台裝置的瀏覽器中進行，不會因為選擇檔案就自動傳到伺服器。" /><Feature icon={BarChart3} title="不只算訊息數" text="從回覆節奏、對話開啟、文字、Emoji、時間與媒體，整理出更有脈絡的互動觀察。" /><Feature icon={EyeOff} title="數據不等於判決" text="所有推測都會標示依據與可信度，不會聲稱知道對方真正想法，也不做心理診斷。" /></div></div></section>
      <section className="section" id="how-it-works"><div className="page-wrap"><div className="section-heading"><div><span className="eyebrow">Simple workflow</span><h2>四步，整理你們的聊天故事</h2></div></div><div className="steps"><Step number="01" title="選擇平台" text="選 LINE、Instagram 或 Messenger，先看對應匯出教學。" /><Step number="02" title="上傳檔案" text="拖曳或選擇檔案，瀏覽器會在本機解析。" /><Step number="03" title="確認身份" text="確認兩位聊天者，告訴我們哪一個是你。" /><Step number="04" title="閱讀報告" text="從總覽到時間軸，慢慢看見互動的不同切面。" /></div></div></section>
      <FAQSection />
    </main><footer className="footer"><div className="page-wrap footer-inner"><div><span>© 2026 AI Chat Analyzer</span><span className="footer-divider">·</span><span>你的聊天，值得被好好理解。</span></div><div className="footer-links"><a href="#faq">常見問題</a><PrivacyTermsTrigger /></div></div></footer>
  </div>;
}
function Feature({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <div className="feature-card"><span className="feature-icon"><Icon size={19} /></span><h3>{title}</h3><p>{text}</p></div>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="step"><span className="step-num">{number}</span><h3>{title}</h3><p>{text}</p></div>; }

function FlowHeader({ onBack, canBack, platform }: { onBack: () => void; canBack: boolean; platform?: Platform }) {
  const current = platform ? "匯入與分析" : "選擇平台";
  return <header className="flow-header"><div className="page-wrap top-nav"><div style={{ display: "flex", alignItems: "center", gap: 17 }}>{canBack && <button className="btn-ghost" aria-label="返回" onClick={onBack} style={{ minHeight: 36, padding: "0 10px" }}><ArrowLeft size={15} /></button>}<Logo /></div><span className="status-pill"><LockKeyhole size={12} />本機優先</span></div><div className="page-wrap" style={{ paddingBottom: 12 }}><div className="progress-line"><span className="progress-dot active" /><b>選擇平台</b><span>—</span><span className={`progress-dot ${platform ? "active" : ""}`} /><span className={platform ? "" : ""}>{current}</span><span>—</span><span className="progress-dot" /><span>分析報告</span></div></div></header>;
}

function PlatformPicker({ onSelect, onBack }: { onSelect: (platform: Platform) => void; onBack: () => void }) {
  return <div className="flow-page"><FlowHeader onBack={onBack} canBack={true} /><main className="flow-main"><div className="flow-title"><span className="eyebrow">Step 01 / source</span><h1>你要分析哪個平台？</h1><p>選擇聊天紀錄的來源，我們會先告訴你怎麼取得可分析的檔案。</p></div><div className="platform-grid">{(Object.keys(PLATFORM_META) as Platform[]).map((platform) => { const meta = PLATFORM_META[platform]; return <button className="platform-card" key={platform} onClick={() => onSelect(platform)}><span className={`platform-logo ${meta.color}`}>{meta.icon}</span><h3>{meta.label}</h3><p>{meta.description}</p><span className="card-arrow">查看匯出教學 <ChevronRight size={14} style={{ verticalAlign: "middle" }} /></span></button>; })}</div><div className="back-row"><button className="btn-ghost" onClick={onBack}><ArrowLeft size={15} />回到首頁</button></div></main></div>;
}

function Guide({ platform, onReady, onBack }: { platform: Platform; onReady: () => void; onBack: () => void }) {
  const meta = PLATFORM_META[platform];
  return <div className="flow-page"><FlowHeader onBack={onBack} canBack platform={platform} /><main className="flow-main"><div className="flow-title"><span className="eyebrow">Step 02 / export guide</span><h1>一步一步準備聊天檔案</h1><p>跟著 {meta.label} 的說明操作即可。平台介面可能隨版本或地區更新，看到相近名稱的功能也可以使用。</p></div><div className="surface-card guide-card"><div className="guide-top"><span className={`platform-logo ${meta.color}`}>{meta.icon}</span><div><h2>{meta.label} 匯出教學</h2><p>推薦格式：{meta.formats}</p></div></div><div className="guide-summary"><div><span>適合使用</span><b>{meta.device}</b></div><div><span>最後要找的檔案</span><b>{meta.filePath}</b></div></div><div className="guide-subsection"><div className="guide-subheading"><span className="guide-heading-icon"><Info size={15} /></span><div><h3>開始前先準備</h3><p>先確認這三件事，可以少走很多回頭路。</p></div></div><ul className="guide-bullets">{meta.preparation.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="guide-subsection"><div className="guide-subheading"><span className="guide-heading-icon"><ArrowRight size={15} /></span><div><h3>詳細操作步驟</h3><p>不確定時，先看步驟標題，再對照你的平台畫面。</p></div></div><div className="guide-list">{meta.steps.map((step, index) => <div className="guide-step" key={step.title}><span className="guide-step-num">{index + 1}</span><div><h3>{step.title}</h3><p>{step.body}</p></div></div>)}</div></div><div className="guide-two-col"><div className="guide-subsection compact"><div className="guide-subheading"><span className="guide-heading-icon"><Check size={15} /></span><div><h3>上傳前檢查</h3></div></div><ul className="guide-bullets">{meta.checks.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="guide-subsection compact"><div className="guide-subheading"><span className="guide-heading-icon warning"><CircleAlert size={15} /></span><div><h3>常見卡關</h3></div></div><ul className="guide-bullets warning-list-guide">{meta.pitfalls.map((item) => <li key={item}>{item}</li>)}</ul></div></div><div className="notice"><Info size={16} style={{ flex: "0 0 auto", marginTop: 2 }} /><span><b>支援格式：{meta.formats}</b><br />只選擇你與另一位對象的對話檔案即可。不要上傳整個帳號資料夾；如果下載檔被拆成多個部分，請在報告的「資料品質」查看日期覆蓋率與警告。</span></div><div className="guide-official"><BookOpen size={15} /><span>想看平台原始說明？</span><a href={meta.officialUrl} target="_blank" rel="noreferrer">查看 {meta.label} 官方教學 <ExternalLinkIcon /></a></div><div className="hero-actions" style={{ justifyContent: "flex-end", marginTop: 24 }}><button className="btn-ghost" onClick={onBack}><ArrowLeft size={15} />換平台</button><button className="btn-primary" onClick={onReady}>我已經準備好了 <ArrowRight size={15} /></button></div></div></main></div>;
}
function ExternalLinkIcon() { return <ChevronRight size={14} style={{ verticalAlign: "middle" }} />; }

function Upload({ platform, onParsed, onBack }: { platform: Platform; onParsed: (result: ParseResult) => void; onBack: () => void }) {
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState("");
  const [parsing, setParsing] = useState(false);
  const [phase, setPhase] = useState("正在讀取聊天紀錄……");
  const inputRef = useRef<HTMLInputElement>(null);
  const read = async (file?: File) => {
    if (!file) return;
    setError(""); setParsing(true);
    try {
      setPhase("正在讀取聊天紀錄……"); await delay(300); setPhase("正在整理訊息……");
      const result = await parseChatFile(platform, file);
      setPhase("正在檢查聊天者……"); await delay(330); onParsed(result);
    } catch (caught) {
      if (caught instanceof ChatParseError) setError(caught.message);
      else setError("這個檔案目前無法辨識，請確認檔案完整後再試一次。");
      setParsing(false);
    }
  };
  if (parsing) return <div className="flow-page"><FlowHeader onBack={onBack} canBack platform={platform} /><main className="flow-main"><div className="surface-card loading-card"><div><div className="loader-ring" /><h2 style={{ margin: 0, fontSize: 19 }}>{phase}</h2><p className="muted">所有基本解析都在你的瀏覽器中進行</p></div></div></main></div>;
  return <div className="flow-page"><FlowHeader onBack={onBack} canBack platform={platform} /><main className="flow-main"><div className="flow-title"><span className="eyebrow">Step 03 / local import</span><h1>把聊天檔案放到這裡</h1><p>你的檔案會先在瀏覽器中解析，不會因為上傳檔案而自動傳送到伺服器。</p></div><div className="upload-panel"><div className={`dropzone ${dragging ? "dragging" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); void read(event.dataTransfer.files?.[0]); }}><div><span className="upload-icon"><UploadCloud size={25} /></span><h3>拖曳檔案到這裡</h3><p>或從你的裝置選擇聊天檔案</p><button className="btn-primary" onClick={() => inputRef.current?.click()}>選擇檔案 <FileUpIcon /></button><input ref={inputRef} type="file" accept=".txt,.json,.html,.htm" hidden onChange={(event) => void read(event.target.files?.[0])} /></div></div><p className="file-hint">支援 {PLATFORM_META[platform].formats} · 檔案不會自動上傳</p>{error && <div className="error-box"><CircleAlert size={17} style={{ flex: "0 0 auto" }} /><span>{error}<br /><button className="nav-link" onClick={onBack}>查看支援格式與匯出教學</button></span></div>}<div className="notice" style={{ marginTop: 25 }}><ShieldCheck size={16} style={{ flex: "0 0 auto", marginTop: 2, color: "var(--mint)" }} /><span><b>隱私提醒</b><br />基本報告不需要登入，也不需要把原始聊天紀錄傳給我們。關閉分頁後，本機解析資料就會被清除。</span></div></div></main></div>;
}
function FileUpIcon() { return <ArrowRight size={15} />; }

function Identify({ parsed, platform, onStart, onBack }: { parsed: ParseResult; platform: Platform; onStart: (id: string) => void; onBack: () => void }) {
  const [selected, setSelected] = useState(parsed.participants[0]?.id ?? "");
  const isGroup = parsed.participants.length > 2;
  return <div className="flow-page"><FlowHeader onBack={onBack} canBack platform={platform} /><main className="flow-main"><div className="flow-title"><span className="eyebrow">Step 04 / make it yours</span><h1>我們找到了一段聊天</h1><p>確認聊天者，接著告訴我們哪一個是你，報告中的「你」才會正確。</p></div><div className="surface-card identify-card">{isGroup && <div className="error-box" style={{ marginTop: 0, marginBottom: 20 }}><Users size={17} style={{ flex: "0 0 auto" }} /><span><b>目前版本主要支援兩人聊天。</b><br />多人聊天分析功能正在規劃中。這份紀錄包含 {parsed.participants.length} 位聊天者，請選擇只有兩人的檔案。</span></div>}<div className="participant-pair"><div className="participant-chip"><Avatar name={parsed.participants[0]?.name ?? "A"} /><strong title={parsed.participants[0]?.name}>{parsed.participants[0]?.name}</strong></div><span className="x-mark">×</span><div className="participant-chip"><Avatar name={parsed.participants[1]?.name ?? "B"} color="yellow" /><strong title={parsed.participants[1]?.name}>{parsed.participants[1]?.name}</strong></div></div><h3 style={{ margin: "0 0 13px", fontSize: 15 }}>哪一個是你？</h3><div className="choice-list">{parsed.participants.slice(0, 2).map((person, index) => <label className="radio-choice" key={person.id}><input type="radio" name="me" checked={selected === person.id} onChange={() => setSelected(person.id)} /><span>我是 <b>{person.name}</b>{index === 0 ? "（A）" : "（B）"}</span></label>)}</div><p className="muted" style={{ margin: "15px 0 0" }}>已辨識 {prettyCount(parsed.messages.length)} 則訊息 · {parsed.participants.length} 位聊天者</p><button className="btn-primary" disabled={isGroup || !selected} onClick={() => onStart(selected)}>開始分析 <Sparkles size={16} /></button></div></main></div>;
}

const PRINT_OPTIONS: { id: TabId; label: string }[] = [
  { id: "overview", label: "總覽" }, { id: "interaction", label: "互動與回覆" }, { id: "emotion", label: "情緒趨勢" }, { id: "heatmap", label: "聊天熱度" }, { id: "drive", label: "聊天帶動力" }, { id: "rhythm", label: "對話節奏" }, { id: "similarity", label: "語言風格" }, { id: "words", label: "文字雲" }, { id: "personality", label: "聊天人格" }, { id: "lifecycle", label: "話題生命週期" }, { id: "conflict", label: "衝突與恢復" }, { id: "silence", label: "沉默分析" }, { id: "links", label: "連結分析" }, { id: "balance", label: "聊天平衡度" }, { id: "highlights", label: "聊天亮點" }, { id: "achievements", label: "聊天成就" }, { id: "timeline", label: "時間軸" }, { id: "recap", label: "年度回顧" }, { id: "quality", label: "資料品質" }, { id: "ai", label: "AI 報告" },
];

function SettingsModal({ report, participants, currentMeId, currentRange, aiEnabled, showSensitive, shareMode, allowShare, onClose, onApply, onClear }: { report: AnalysisReport; participants: { id: string; name: string }[]; currentMeId: string; currentRange: AnalysisRange; aiEnabled: boolean; showSensitive: boolean; shareMode: ShareMode; allowShare: boolean; onClose: () => void; onApply: (meId: string, range: AnalysisRange, ai: boolean, sensitive: boolean, mode: ShareMode, share: boolean) => void; onClear: () => void }) {
  const [meId, setMeId] = useState(currentMeId); const [range, setRange] = useState(currentRange); const [ai, setAi] = useState(aiEnabled); const [sensitive, setSensitive] = useState(showSensitive); const [mode, setMode] = useState(shareMode); const [share, setShare] = useState(allowShare);
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal modal-large settings-modal"><div className="modal-heading"><span className="feature-icon"><Gauge size={19} /></span><div><h3>分析設定</h3><p>不重新上傳檔案，也能調整這份報告</p></div><button className="btn-ghost modal-close" onClick={onClose}><X size={16} /></button></div><div className="settings-grid"><section><h4>我是誰？</h4><div className="choice-list">{participants.slice(0, 2).map((person) => <label className="radio-choice" key={person.id}><input type="radio" name="settings-me" checked={meId === person.id} onChange={() => setMeId(person.id)} /><span>{person.name}</span></label>)}</div></section><section><h4>分析期間</h4><select className="settings-select" value={range.preset} onChange={(event) => setRange({ preset: event.target.value as RangePreset, start: range.start, end: range.end })}><option value="all">全部紀錄</option><option value="thisYear">今年</option><option value="lastYear">去年</option><option value="last12">最近一年</option><option value="custom">自訂日期</option></select>{range.preset === "custom" && <div className="date-inputs"><label>開始<input type="date" value={dateInputValue(range.start)} onChange={(event) => setRange({ ...range, start: event.target.value })} /></label><label>結束<input type="date" value={dateInputValue(range.end)} onChange={(event) => setRange({ ...range, end: event.target.value })} /></label></div>}</section><section><h4>功能偏好</h4><label className="toggle-row"><input type="checkbox" checked={ai} onChange={(event) => setAi(event.target.checked)} /><span><b>允許 AI 功能</b><small>仍需每次明確同意後才送出</small></span></label><label className="toggle-row"><input type="checkbox" checked={sensitive} onChange={(event) => setSensitive(event.target.checked)} /><span><b>顯示敏感分析</b><small>疑似衝突、恢復與互動投入</small></span></label><label className="toggle-row"><input type="checkbox" checked={share} onChange={(event) => setShare(event.target.checked)} /><span><b>允許建立分享報告</b><small>分享內容不含完整原始聊天</small></span></label></section><section><h4>分享內容</h4><select className="settings-select" value={mode} onChange={(event) => setMode(event.target.value as ShareMode)}><option value="full">完整統計分享</option><option value="recap">年度回顧分享</option><option value="achievements">只分享成就</option></select><p className="settings-help">建立分享時會依這裡的選擇顯示章節，不會公開原始完整訊息。</p></section></div><div className="notice"><ShieldCheck size={16} style={{ flex: "0 0 auto" }} /><span>目前分析來自瀏覽器記憶體中的 {report.overview.total.toLocaleString()} 則訊息。清除本機資料後，這份未分享的報告將無法恢復。</span></div><div className="modal-actions"><button className="btn-ghost" onClick={onClear}>清除本機資料</button><button className="btn-primary" onClick={() => onApply(meId, range, ai, sensitive, mode, share)}>套用並重新分析</button></div></div></div>;
}

function PrintOptionsModal({ selected, onClose, onPrint, onToggle }: { selected: TabId[]; onClose: () => void; onPrint: () => void; onToggle: (id: TabId) => void }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal modal-large settings-modal"><div className="modal-heading"><span className="feature-icon"><FileDown size={19} /></span><div><h3>選擇 PDF 章節</h3><p>列印功能會在你的瀏覽器中產生 PDF，不會上傳聊天內容</p></div><button className="btn-ghost modal-close" onClick={onClose}><X size={16} /></button></div><div className="print-options">{PRINT_OPTIONS.map((item) => <label className="toggle-row" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} /><span><b>{item.label}</b></span></label>)}</div><div className="modal-actions"><button className="btn-ghost" onClick={onClose}>取消</button><button className="btn-primary" disabled={!selected.length} onClick={onPrint}>列印所選章節 <FileDown size={15} /></button></div></div></div>; }

function ReportHeader({ report, currentRange, onPrint, onShare, onSettings, shareLink, shareBusy, shareDisabled, shareMode }: { report: AnalysisReport; currentRange: AnalysisRange; onPrint: () => void; onShare: () => void; onSettings: () => void; shareLink: string; shareBusy: boolean; shareDisabled: boolean; shareMode: ShareMode }) {
  return <><div className="report-main-header"><div><span className="eyebrow">{report.platformLabel} · local report</span><h2>{report.me.name} <span style={{ color: "#a2adbd", fontWeight: 400 }}>×</span> {report.them.name}</h2><p>{report.overview.startDate} — {report.overview.endDate} · {report.quality.note}</p></div><span className="status-pill"><ShieldCheck size={12} />原始資料未離開裝置</span></div><div className="report-actions no-print"><button className="btn-ghost" onClick={onPrint}><FileDown size={15} />下載 PDF</button><button className="btn-ghost" onClick={onSettings}><Gauge size={15} />分析設定</button><button className="btn-primary" onClick={onShare} disabled={shareBusy || shareDisabled} title={shareDisabled ? "已在分析設定中關閉分享" : undefined}>{shareBusy ? "正在建立…" : <><Share2 size={15} />{shareDisabled ? "分享已關閉" : "建立分享報告"}</>}</button>{shareLink && <button className="btn-secondary" onClick={() => void navigator.clipboard?.writeText(shareLink)}><Link2 size={14} />複製連結</button>}</div><div className="report-meta-line no-print"><span>目前期間：{rangeLabel(currentRange)}</span><span>分享模式：{shareMode === "full" ? "完整統計" : shareMode === "recap" ? "年度回顧" : "只分享成就"}</span></div>{shareLink && <div className="notice no-print" style={{ marginBottom: 15 }}><CircleCheck size={16} style={{ color: "var(--mint)", flex: "0 0 auto" }} /><span>分享報告已建立：<a className="nav-link" href={shareLink} target="_blank" rel="noreferrer">{shareLink}</a></span></div>}</>;
}

function Sidebar({ active, onChange }: { active: TabId; onChange: (tab: TabId) => void }) {
  return <aside className="report-sidebar"><Logo /><h1>聊天分析報告</h1><p>把數據整理成一個可以慢慢閱讀的故事。</p><nav className="sidebar-nav">{TABS.map(({ id, label, icon: Icon }) => <button className={active === id ? "active" : ""} key={id} onClick={() => onChange(id)}><Icon size={15} />{label}</button>)}</nav></aside>;
}
function ReportSectionTitle({ title, detail }: { title: string; detail?: string }) { return <div className="report-section-title"><h3>{title}</h3>{detail && <span>{detail}</span>}</div>; }
function StatCard({ label, value, sub }: { label: string; value: string; sub?: string }) { return <div className="surface-card stat-card"><span className="stat-label">{label}</span><div className="stat-value">{value}</div>{sub && <div className="stat-sub">{sub}</div>}</div>; }
function BarRow({ label, value, max, color, suffix }: { label: string; value: number; max: number; color?: "mint" | "coral"; suffix?: string }) { return <div className="distribution-row"><div className="distribution-label"><span>{label}</span><b>{value.toLocaleString()}{suffix ?? ""}</b></div><div className="bar-track"><div className={`bar-fill ${color ?? ""}`} style={{ width: `${Math.max(2, (value / Math.max(1, max)) * 100)}%` }} /></div></div>; }

function Overview({ report, onGo }: { report: AnalysisReport; onGo: (tab: TabId) => void }) {
  return <><div className="stats-grid"><StatCard label="總訊息數" value={prettyCount(report.overview.total)} sub={`${report.overview.perDay} 則 / 天`} /><StatCard label="聊天期間" value={`${report.overview.durationDays} 天`} sub={`${report.overview.startDate} 開始`} /><StatCard label="最活躍日期" value={report.overview.activeDate} sub="訊息最密集的一天" /><StatCard label="最常聊天時段" value={report.overview.activeHour} sub="依訊息時間統計" /></div><ReportSectionTitle title="這段聊天的第一眼" detail="客觀數據" /><div className="two-col"><div className="surface-card card-pad"><div className="card-title"><h4><MessageCircle size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />訊息分布</h4><span className="status-pill">{report.overview.total.toLocaleString()} 則</span></div><div className="distribution"><BarRow label={shortName(report.me.name)} value={report.overview.myMessages} max={report.overview.total} /><BarRow label={shortName(report.them.name)} value={report.overview.theirMessages} max={report.overview.total} color="mint" /></div><p className="muted" style={{ margin: "18px 0 0" }}>訊息量是描述紀錄的數據，不直接代表誰比較在意。</p></div><div className="surface-card card-pad"><div className="card-title"><h4><Flame size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "#e6a942" }} />聊天節奏</h4></div><div className="metric-pair"><div className="metric-box"><span>最長連續聊天</span><strong>{report.overview.longestStreakHours ? `${report.overview.longestStreakHours} 小時` : "—"}</strong></div><div className="metric-box"><span>期間平均</span><strong>{report.overview.perDay} 則/天</strong></div></div><p className="muted" style={{ margin: "16px 0 0" }}>從 {report.overview.startDate} 到 {report.overview.endDate}，共觀察到 {report.overview.durationDays} 天的紀錄。</p></div></div><ReportSectionTitle title="繼續探索" detail="報告導覽" /><div className="three-col">{[["interaction", "誰比較常把話題往前推？", Activity], ["response", "你們通常多久回覆？", Timer], ["recap", "把這段聊天做成回顧卡", Sparkles]].map(([id, title, Icon]) => <button className="surface-card feature-card" style={{ textAlign: "left" }} key={id as string} onClick={() => onGo(id as TabId)}><span className="feature-icon"><Icon size={18} /></span><h3>{title as string}</h3><p>查看這一段分析 →</p></button>)}</div></>;
}

function Interaction({ report }: { report: AnalysisReport }) {
  return <><ReportSectionTitle title="誰比較主動？" detail="行為觀察，不是關係判決" /><div className="two-col"><div className="surface-card card-pad"><div className="card-title"><h4><Target size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />主動程度</h4><span className="status-pill">可觀察互動</span></div><div className="metric-pair"><div className="metric-box"><span>{shortName(report.me.name)}</span><strong style={{ color: "var(--blue)" }}>{percent(report.initiative.me)}</strong></div><div className="metric-box"><span>{shortName(report.them.name)}</span><strong style={{ color: "var(--mint)" }}>{percent(report.initiative.them)}</strong></div></div><div style={{ marginTop: 18 }}><div className="bar-track" style={{ height: 13 }}><div style={{ width: `${report.initiative.me}%`, height: "100%", borderRadius: "inherit", background: "linear-gradient(90deg, #5c8fe9, #2d6cdf)" }} /></div></div><p className="muted" style={{ margin: "16px 0 0" }}>此數值根據聊天紀錄中的可觀察互動行為計算，包含重新開啟對話、提出問題與分享內容。</p></div><div className="surface-card card-pad"><div className="card-title"><h4><Info size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "#a27a3d" }} />分析依據</h4></div><ul className="bullet-list">{report.initiative.basis.map((basis) => <li key={basis}>{basis}</li>)}</ul><div className="notice" style={{ marginTop: 18 }}>主動程度高，不代表比較在意；它只描述在這份紀錄中看得到的互動動作。</div></div></div><ReportSectionTitle title="互動投入" detail="上下文啟發式分析" /><div className="two-col"><EngagementCard name={report.me.name} score={report.engagement.me.score} confidence={report.engagement.me.confidence} color="blue" /><EngagementCard name={report.them.name} score={report.engagement.them.score} confidence={report.engagement.them.confidence} color="mint" /></div><div className="notice" style={{ marginTop: 15 }}>我們不把「字數短」直接當成敷衍；這裡會比較回覆前是否有問題或情緒訊號、回覆內容與是否延續話題。AI 是根據聊天內容推測，並不代表對方真實想法。</div></>;
}
function EngagementCard({ name, score, confidence, color }: { name: string; score: number; confidence: number; color: "blue" | "mint" }) { return <div className="surface-card card-pad"><div className="card-title"><h4>{name} · 互動投入</h4><span className="status-pill">{levelText(score)}</span></div><div className="distribution"><BarRow label="互動投入指數" value={score} max={100} color={color === "mint" ? "mint" : undefined} suffix=" / 100" /></div><p className="muted" style={{ margin: "14px 0 0" }}>推測可信度 {confidence}% · 以訊息上下文與平常風格相對觀察。</p></div>; }

function Response({ report }: { report: AnalysisReport }) {
  const r = report.response;
  return <><ReportSectionTitle title="回覆有多快？" detail="以有下一則回覆的片段計算" /><div className="two-col"><ResponsePerson name={report.me.name} data={r.me} /><ResponsePerson name={report.them.name} data={r.them} /></div><ReportSectionTitle title="不同時段的回覆中位數" detail="中位數較不受極端等待影響" /><div className="surface-card card-pad"><div className="bar-chart">{r.byPeriod.map((period) => { const value = Math.max(period.me, period.them); return <div className="bar-column" key={period.label}><i style={{ height: `${Math.max(3, (value / Math.max(1, ...r.byPeriod.flatMap((item) => [item.me, item.them]))) * 120)}px`, background: period.me >= period.them ? "#6d9bea" : "#55b997" }} /><small>{period.label}</small></div>; })}</div><div className="metric-pair" style={{ marginTop: 18 }}>{r.byPeriod.map((period) => <div className="metric-box" key={period.label}><span>{period.label}</span><strong style={{ fontSize: 13 }}>{period.me ? formatMinutesForReport(period.me) : "—"} <small style={{ color: "#8f9bad", fontWeight: 400 }}> / {period.them ? formatMinutesForReport(period.them) : "—"}</small></strong></div>)}</div></div><ReportSectionTitle title="疑似長時間未回覆" detail="不是已讀狀態" /><div className="surface-card card-pad"><div className="metric-pair"><div className="metric-box"><span>{report.me.name}</span><strong>{report.unanswered.me} 次</strong></div><div className="metric-box"><span>{report.them.name}</span><strong>{report.unanswered.them} 次</strong></div></div><p className="muted" style={{ margin: "15px 0 0" }}><EyeOff size={13} style={{ verticalAlign: "middle", marginRight: 5 }} />{report.unanswered.note}</p></div></>;
}
function ResponsePerson({ name, data }: { name: string; data: AnalysisReport["response"]["me"] }) { return <div className="surface-card card-pad"><div className="card-title"><h4><Timer size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />{name}</h4><span className="status-pill">{data.count} 次回覆</span></div><div className="metric-pair"><div className="metric-box"><span>平均</span><strong>{formatMinutesForReport(data.average)}</strong></div><div className="metric-box"><span>中位數</span><strong>{formatMinutesForReport(data.median)}</strong></div><div className="metric-box"><span>最快</span><strong>{formatMinutesForReport(data.fastest)}</strong></div><div className="metric-box"><span>最慢</span><strong>{formatMinutesForReport(data.slowest)}</strong></div></div></div>; }

function Habits({ report }: { report: AnalysisReport }) {
  const max = maxValue(report.time.hours.map((item) => item.value));
  const media = (who: "me" | "them") => report.media[who];
  return <><ReportSectionTitle title="你們都在什麼時候聊天？" detail="依訊息發送時間統計" /><div className="two-col"><div className="surface-card card-pad"><div className="card-title"><h4><Clock3 size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />24 小時分布</h4></div><div className="bar-chart">{report.time.hours.map((item) => <div className="bar-column" key={item.label}><i style={{ height: `${Math.max(3, (item.value / max) * 125)}px` }} /><small>{Number(item.label.slice(0, 2)) % 4 === 0 ? item.label.slice(0, 2) : ""}</small></div>)}</div></div><div className="surface-card card-pad"><div className="card-title"><h4><CalendarDays size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />星期分布</h4></div><div className="distribution">{report.time.weekdays.map((item) => <BarRow key={item.label} label={item.label} value={item.value} max={maxValue(report.time.weekdays.map((row) => row.value))} />)}</div></div></div><ReportSectionTitle title="聊天媒體" detail="V1 只統計數量，不分析內容" /><div className="two-col"><MediaCard name={report.me.name} data={media("me")} /><MediaCard name={report.them.name} data={media("them")} /></div><ReportSectionTitle title="聊天熱區" detail="星期 × 小時" /><div className="surface-card card-pad"><div className="heatmap-wrap"><div className="heatmap"><span /><>{Array.from({ length: 24 }, (_, hour) => <span className="heat-hour" key={hour}>{hour % 4 === 0 ? `${hour}` : ""}</span>)}</>{report.time.heatmap.map((row, weekday) => <><span className="heat-label" key={`label-${weekday}`}>{["日", "一", "二", "三", "四", "五", "六"][weekday]}</span>{row.map((value, hour) => <span className="heat-cell" data-level={value >= 8 ? 4 : value >= 4 ? 3 : value >= 2 ? 2 : value ? 1 : 0} title={`${WEEKDAY_TEXT(weekday)} ${hour}:00 · ${value} 則`} key={`${weekday}-${hour}`} />)}</>)}</div></div></div></>;
}
function WEEKDAY_TEXT(index: number) { return ["週日", "週一", "週二", "週三", "週四", "週五", "週六"][index]; }
function MediaCard({ name, data }: { name: string; data: Record<"image" | "video" | "audio" | "sticker" | "file", number> }) { return <div className="surface-card card-pad"><div className="card-title"><h4>{name}</h4></div><div className="media-grid">{mediaItems.map(({ key, icon: Icon, label }) => <div className="media-item" key={key}><Icon size={17} color="#6f91d7" /><span>{label}</span><strong>{data[key]}</strong></div>)}</div></div>; }

function Words({ report }: { report: AnalysisReport }) {
  const [filter, setFilter] = useState<"all" | "me" | "them">("all");
  const [selected, setSelected] = useState<string | null>(null);
  const words = report.words.filter((word) => filter === "all" || (filter === "me" ? word.me > 0 : word.them > 0));
  const max = maxValue(words.slice(0, 35).map((word) => word.total));
  const chosen = report.words.find((word) => word.word === selected);
  return <><ReportSectionTitle title="你們的聊天文字雲" detail="點選一個詞查看分布" /><div className="surface-card"><div style={{ display: "flex", gap: 7, padding: "17px 17px 0" }}>{([ ["all", "全部"], ["me", report.me.name], ["them", report.them.name] ] as const).map(([value, label]) => <button className={filter === value ? "btn-secondary" : "btn-ghost"} style={{ minHeight: 33, padding: "0 11px", fontSize: 11 }} key={value} onClick={() => setFilter(value)}>{label}</button>)}</div><div className="word-cloud">{words.slice(0, 35).map((word, index) => <button key={word.word} style={{ fontSize: `${13 + (word.total / max) * 25}px`, opacity: `${Math.max(.62, 1 - index * .009)}` }} onClick={() => setSelected(word.word)}>{word.word}</button>)}</div></div>{chosen && <div className="surface-card card-pad" style={{ marginTop: 14 }}><div className="card-title"><h4>「{chosen.word}」在你們的聊天裡</h4><button className="btn-ghost" style={{ minHeight: 30, padding: "0 8px" }} onClick={() => setSelected(null)}><X size={14} /></button></div><div className="metric-pair"><div className="metric-box"><span>總共</span><strong>{chosen.total} 次</strong></div><div className="metric-box"><span>{report.me.name}</span><strong>{chosen.me}</strong></div><div className="metric-box"><span>{report.them.name}</span><strong>{chosen.them}</strong></div></div></div>}<div className="notice" style={{ marginTop: 15 }}><Info size={16} style={{ flex: "0 0 auto" }} /><span>中文詞語以繁體中文斷詞規則整理，並排除常見無意義詞。詞頻是統計，不代表話題重要性。</span></div></>;
}

function Personality({ report }: { report: AnalysisReport }) {
  return <><ReportSectionTitle title="你們的聊天人格" detail="行為標籤，不是心理診斷" /><div className="two-col"><PersonalityCard profile={report.personalities.me} color="blue" /><PersonalityCard profile={report.personalities.them} color="yellow" /></div><div className="notice" style={{ marginTop: 15 }}><ShieldCheck size={16} style={{ flex: "0 0 auto", color: "var(--blue)" }} /><span>「聊天人格」只根據發起、回覆、文字長度、時間與 Emoji 等可觀察行為分類，不能代表完整個性或真實想法。</span></div></>;
}
function PersonalityCard({ profile, color }: { profile: AnalysisReport["personalities"]["me"]; color: "blue" | "yellow" }) { return <div className="surface-card person-card"><div className="person-title"><Avatar name={profile.name} color={color === "yellow" ? "yellow" : "blue"} /><div><h4>{profile.name}</h4><span className="muted">聊天行為輪廓</span></div></div><div className="tag-list">{profile.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><ul className="traits">{profile.traits.map((trait) => <li key={trait}>{trait}</li>)}</ul></div>; }

function downloadRecapImage(report: AnalysisReport) {
  const canvas = document.createElement("canvas"); canvas.width = 1080; canvas.height = 1500; const context = canvas.getContext("2d"); if (!context) return;
  context.fillStyle = "#1f4b9d"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#c6d7fa"; context.font = "700 28px sans-serif"; context.fillText(`${report.overview.startDate.slice(0, 4)} CHAT RECAP`, 82, 105); context.fillStyle = "#ffffff"; context.font = "800 58px sans-serif"; context.fillText("你們的聊天故事", 82, 205); context.font = "400 28px sans-serif"; context.fillStyle = "#d6e2fc"; context.fillText(`${report.me.name} × ${report.them.name}`, 82, 258);
  const lines = [["訊息總數", `💬 ${report.overview.total.toLocaleString()}`], ["平均每天", `⏱ ${report.overview.perDay} 則`], ["最常聊天時段", `🌙 ${report.overview.activeHour}`], ["最常使用 Emoji", report.emoji.byEmoji[0]?.emoji ?? "—"], ["最常用詞", report.v2.highlights.topWord], ["最活躍月份", report.time.months.sort((a, b) => b.value - a.value)[0]?.label ?? "—"], ["最長沉默", report.v2.highlights.longestSilence], ["最常話題", report.v2.highlights.topTopic]];
  lines.forEach(([label, value], index) => { const y = 390 + index * 125; context.fillStyle = "rgba(255,255,255,.18)"; context.fillRect(82, y - 36, 916, 1); context.fillStyle = "#b9cefa"; context.font = "400 23px sans-serif"; context.fillText(label, 82, y); context.fillStyle = "#ffffff"; context.font = "700 32px sans-serif"; context.fillText(value, 82, y + 48); }); context.fillStyle = "#b9cefa"; context.font = "400 20px sans-serif"; context.fillText("AI Chat Analyzer · 由本機分析產生", 82, 1430);
  canvas.toBlob((blob) => { if (!blob) return; const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "chat-recap.png"; link.click(); URL.revokeObjectURL(link.href); }, "image/png");
}

function Topics({ report }: { report: AnalysisReport }) { const max = maxValue(report.topics.map((item) => item.count)); return <><ReportSectionTitle title="你們都在聊什麼？" detail="文字詞彙的主題聚合" /><div className="two-col"><div className="surface-card card-pad"><div className="card-title"><h4><TrendingUp size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />TOP {report.topics.length}</h4><span className="status-pill">從聊天文字整理</span></div><div className="topic-list">{report.topics.length ? report.topics.map((topic, index) => <div className="topic-row" key={topic.name}><span className="topic-rank">0{index + 1}</span><span className="topic-name">{topic.name}</span><span className="topic-count">{topic.count} 次</span><div className="bar-track"><div className="bar-fill" style={{ width: `${(topic.count / max) * 100}%` }} /></div></div>) : <p className="muted">文字資料還不夠，暫時找不到穩定主題。</p>}</div></div><div className="surface-card card-pad"><div className="card-title"><h4><BookOpen size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />怎麼讀這張卡？</h4></div><p className="muted">主題是由繁體中文詞彙與常見聊天語境聚合而來。它描述「聊過什麼」，不判斷這些話題對你們的意義。</p><div className="notice" style={{ marginTop: 15 }}>啟用 AI 後，AI 可以在這些實際詞彙之上，嘗試提供更自然的主題名稱，但仍不能創造不存在的事件。</div></div></div></>; }

function Conflict({ report }: { report: AnalysisReport }) { const conflicts = report.events.filter((event) => event.type === "conflict" || event.type === "recovery"); return <><ReportSectionTitle title="衝突與恢復" detail="疑似事件 · 有依據才標記" /><div className="surface-card card-pad"><div className="card-title"><h4><RefreshCw size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />我們怎麼判讀？</h4></div><p className="muted" style={{ margin: 0 }}>不會只搜尋負面詞。系統會把連續語氣強度、訊息長度與回覆節奏放在同一段上下文裡觀察，只有訊號同時出現才會標示「疑似」。後續是否重新聊天，也只描述互動是否恢復，不能代表雙方已經和好。</p></div>{conflicts.length ? <div className="surface-card card-pad" style={{ marginTop: 15 }}><div className="event-list">{conflicts.map((event) => <EventRow event={event} key={event.id} />)}</div></div> : <div className="surface-card card-pad" style={{ marginTop: 15 }}><div className="notice"><CircleCheck size={16} style={{ color: "var(--mint)" }} /><span>在目前紀錄裡，沒有足夠的連續訊號標記疑似衝突。沒有標記不代表沒有情緒，只代表資料不足以可靠判斷。</span></div></div>}<div className="notice" style={{ marginTop: 15 }}><EyeOff size={16} style={{ flex: "0 0 auto" }} /><span>匯出聊天通常沒有聲音、表情與已讀狀態；所有事件都是從聊天特徵推測，請保留自己的理解。</span></div></>; }
function EventRow({ event }: { event: AnalysisReport["events"][number] }) { return <div className={`event ${event.type}`}><span className="event-date">{event.date}</span><h4>{event.title} {event.confidence && <span className="confidence">可信度 {event.confidence}%</span>}</h4><p>{event.description}</p>{event.reasons && <ul className="bullet-list" style={{ marginTop: 9, gap: 2, fontSize: 11 }}>{event.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>}</div>; }

function Timeline({ report }: { report: AnalysisReport }) { return <><ReportSectionTitle title="你們的聊天故事" detail="依時間排序的可觀察事件" /><div className="surface-card card-pad"><div className="event-list">{report.events.map((event) => <EventRow event={event} key={event.id} />)}</div></div><div className="notice" style={{ marginTop: 15 }}><CalendarDays size={16} style={{ flex: "0 0 auto" }} /><span>事件由訊息時間、互動密度與上下文訊號整理。點狀事件不是完整故事，也不會取代你對這段關係的記憶。</span></div></>; }

function Recap({ report }: { report: AnalysisReport }) { const topEmoji = report.emoji.byEmoji[0]?.emoji ?? "—"; const topMonth = [...report.time.months].sort((a, b) => b.value - a.value)[0]; return <><ReportSectionTitle title="年度回顧卡" detail="把一段聊天留下來" /><div className="surface-card recap"><span className="eyebrow">{report.overview.startDate.slice(0, 4)} CHAT RECAP</span><h3>{report.me.name} × {report.them.name}</h3><p>你們在這段時間，留下了不少訊息與互動片段。</p><button className="btn-secondary no-print" style={{ marginTop: 17 }} onClick={() => downloadRecapImage(report)}><Download size={14} />下載手機長圖</button><div className="recap-grid"><div className="recap-item"><span>訊息總數</span><strong>💬 {prettyCount(report.overview.total)}</strong></div><div className="recap-item"><span>平均每天</span><strong>⏱️ {report.overview.perDay} 則</strong></div><div className="recap-item"><span>最常回覆中位數</span><strong>↔ {formatMinutesForReport(Math.min(report.response.me.median || Infinity, report.response.them.median || Infinity) === Infinity ? 0 : Math.min(report.response.me.median || Infinity, report.response.them.median || Infinity))}</strong></div><div className="recap-item"><span>最常使用 Emoji</span><strong>{topEmoji}</strong></div><div className="recap-item"><span>最常聊天時段</span><strong>🌙 {report.overview.activeHour}</strong></div><div className="recap-item"><span>最活躍月份</span><strong>📅 {topMonth?.label ?? "—"}</strong></div></div></div><div className="two-col" style={{ marginTop: 15 }}><div className="surface-card card-pad"><div className="card-title"><h4>這張卡的數據來源</h4></div><p className="muted">期間、訊息量、回覆中位數、Emoji、活躍時段與月份，全部取自這份已解析的聊天檔案。</p></div><div className="surface-card card-pad"><div className="card-title"><h4>留給未來的提醒</h4></div><p className="muted">漂亮的數字可以幫你回想，但它們不會替你定義這段關係。</p></div></div></>; }

function AiReport({ report, ai, onEnable }: { report: AnalysisReport; ai: AiAnalysis | null; onEnable: () => void }) { if (!ai) return <><ReportSectionTitle title="想知道更多？" detail="AI 深度分析是選用功能" /><div className="surface-card ai-card"><div className="ai-heading"><span className="ai-symbol"><Bot size={20} /></span><div><h3>讓 AI 讀懂對話上下文</h3><p style={{ margin: "7px 0 0" }}>基本統計已在你的裝置完成。如果你想要更自然的互動摘要、氣氛與聊天特色，可以主動啟用 AI 深度分析。</p></div></div><button className="btn-primary" style={{ marginTop: 11 }} onClick={onEnable}>啟用 AI 深度分析 <Sparkles size={15} /></button><div className="caution"><LockKeyhole size={13} style={{ verticalAlign: "middle", marginRight: 4 }} />啟用前會再次顯示資料使用說明。未經你的同意，不會送出任何對話資料。</div></div></>; return <><ReportSectionTitle title="AI 深度分析" detail={`${ai.provider === "OpenAI" ? "OpenAI" : "保守摘要模式"} · 可信度 ${ai.confidence}%`} /><div className="surface-card ai-card"><div className="ai-heading"><span className="ai-symbol"><Bot size={20} /></span><div><h3>🤖 AI 偷看完你們的聊天後：</h3><p style={{ margin: "7px 0 0" }}>以下內容只使用去識別化的統計與互動摘要，沒有送出原始檔案。</p></div></div><div className="quote" style={{ marginTop: 22 }}>{ai.summary}</div><ReportSectionTitle title="互動氣氛" detail="模型觀察" /><p>{ai.atmosphere}</p><ReportSectionTitle title="有趣的聊天觀察" /><ul className="bullet-list">{ai.observations.map((observation) => <li key={observation}>{observation}</li>)}</ul><div className="caution"><strong>⚠️ 重要提醒</strong><br />{ai.cautions.join(" ") || "以上內容為 AI 根據聊天紀錄推測，不代表對方真實想法。"}<br />這不是對你們關係的判決，而是根據聊天紀錄產生的互動分析。</div></div></>; }

function ConsentModal({ onCancel, onConfirm, loading, error }: { onCancel: () => void; onConfirm: () => void; loading: boolean; error: string }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="ai-heading"><span className="ai-symbol"><ShieldCheck size={19} /></span><div><h3>啟用 AI 深度分析？</h3><p style={{ margin: 0 }}>這是一個需要你主動選擇的功能。</p></div></div><p>AI 深度分析需要將<strong>去除姓名的必要分析資料</strong>傳送給 AI 服務，包括訊息量、回覆節奏、主題、行為標籤與疑似事件摘要。原始聊天檔案不會上傳，也不會永久保存。</p><div className="notice"><LockKeyhole size={16} style={{ flex: "0 0 auto" }} /><span>送出前已移除姓名，並且不包含完整聊天內容、電話、Email 或地址。</span></div>{error && <div className="error-box">{error}</div>}<div className="modal-actions"><button className="btn-ghost" onClick={onCancel} disabled={loading}>先不要</button><button className="btn-primary" onClick={onConfirm} disabled={loading}>{loading ? "AI 正在整理上下文…" : "我了解，開始 AI 分析"}</button></div></div></div>; }

function SensitiveHidden() { return <><ReportSectionTitle title="敏感分析已隱藏" detail="可在分析設定中開啟" /><div className="surface-card card-pad"><div className="notice"><EyeOff size={16} /><span>你目前選擇不顯示互動投入、疑似衝突與恢復等推測型結果。客觀統計仍然可以查看。</span></div></div></>; }

function AskConsentModal({ request, onCancel, onConfirm, loading, error }: { request: { question: string } | null; onCancel: () => void; onConfirm: () => void; loading: boolean; error: string }) { if (!request) return null; return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="ai-heading"><span className="ai-symbol"><ShieldCheck size={19} /></span><div><h3>送出這個聊天問題？</h3><p style={{ margin: 0 }}>AI 問答需要你的主動同意。</p></div></div><p>你的問題會和<strong>去識別化的分析報告摘要</strong>一起送給 AI 服務。原始聊天檔案、完整對話、姓名、電話與 Email 都不會送出。</p><div className="ask-question-preview">「{request.question}」</div><div className="notice"><LockKeyhole size={16} style={{ flex: "0 0 auto" }} /><span>沒有按下確認前，不會傳送任何資料。你也可以只使用本機的「聊天記憶搜尋」。</span></div>{error && <div className="error-box">{error}</div>}<div className="modal-actions"><button className="btn-ghost" onClick={onCancel} disabled={loading}>先不要</button><button className="btn-primary" onClick={onConfirm} disabled={loading}>{loading ? "AI 正在整理…" : "我了解，送出問題"}</button></div></div></div>; }

function MobileNav({ active, onChange }: { active: TabId; onChange: (tab: TabId) => void }) { const visible = TABS.filter((_, index) => [0, 1, 2, 4, 6, 10].includes(index)); return <nav className="mobile-nav no-print">{visible.map(({ id, label, icon: Icon }) => <button className={active === id ? "active" : ""} key={id} onClick={() => onChange(id)}><Icon size={15} /><br />{label}</button>)}</nav>; }

function ReportPage({ report, messages, participants, currentMeId, currentRange, onReanalyze, onReset }: { report: AnalysisReport; messages: NormalizedMessage[]; participants: { id: string; name: string }[]; currentMeId: string; currentRange: AnalysisRange; onReanalyze: (meId: string, range: AnalysisRange) => void; onReset: () => void }) {
  const [active, setActive] = useState<TabId>("overview");
  const [ai, setAi] = useState<AiAnalysis | null>(null);
  const [aiOpen, setAiOpen] = useState(false); const [aiLoading, setAiLoading] = useState(false); const [aiError, setAiError] = useState("");
  const [askRequest, setAskRequest] = useState<{ question: string; resolve: (answer: string) => void } | null>(null); const [askLoading, setAskLoading] = useState(false); const [askError, setAskError] = useState("");
  const [shareLink, setShareLink] = useState(""); const [shareBusy, setShareBusy] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false); const [printOpen, setPrintOpen] = useState(false); const [showSensitive, setShowSensitive] = useState(true); const [aiEnabled, setAiEnabled] = useState(true); const [allowShare, setAllowShare] = useState(true); const [shareMode, setShareMode] = useState<ShareMode>("full"); const [printSections, setPrintSections] = useState<TabId[]>(PRINT_OPTIONS.map((item) => item.id));
  const goto = (tab: TabId) => { setActive(tab); window.setTimeout(() => document.getElementById(`report-${tab}`)?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); };
  const runAi = async () => {
    setAiLoading(true); setAiError("");
    try { const response = await fetch("/api/ai/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ report }) }); const data = await response.json() as AiAnalysis & { error?: string }; if (!response.ok) throw new Error(data.error || "AI 暫時無法完成分析。"); setAi(data); setAiOpen(false); setActive("ai"); } catch (error) { setAiError(error instanceof Error ? error.message : "AI 暫時無法完成分析，請稍後再試。"); } finally { setAiLoading(false); }
  };
  const askAi = (question: string) => new Promise<string>((resolve) => { setAskError(""); setAskRequest({ question, resolve }); });
  const confirmAsk = async () => {
    if (!askRequest) return;
    setAskLoading(true); setAskError("");
    try { const response = await fetch("/api/ai/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ report, question: askRequest.question }) }); const data = await response.json() as { answer?: string; error?: string }; if (!response.ok || !data.answer) throw new Error(data.error || "AI 問答暫時無法完成。"); askRequest.resolve(data.answer); setAskRequest(null); } catch (error) { setAskError(error instanceof Error ? error.message : "AI 問答暫時無法完成。"); } finally { setAskLoading(false); }
  };
  const share = async () => {
    setShareBusy(true);
    try {
      const safeReport = { ...report, me: { ...report.me, name: "PERSON_A" }, them: { ...report.them, name: "PERSON_B" }, personalities: { me: { ...report.personalities.me, name: "PERSON_A" }, them: { ...report.personalities.them, name: "PERSON_B" } } };
      const response = await fetch("/api/share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ report: safeReport, ai, mode: shareMode }) }); const data = await response.json() as { id?: string; error?: string }; if (!response.ok || !data.id) throw new Error(data.error || "目前無法建立分享報告。"); setShareLink(`${window.location.origin}/report/${data.id}`);
    } catch (error) { window.alert(error instanceof Error ? error.message : "目前無法建立分享報告，請稍後再試。"); } finally { setShareBusy(false); }
  };
  const applySettings = (nextMeId: string, nextRange: AnalysisRange, nextAi: boolean, nextSensitive: boolean, nextMode: ShareMode, nextShare: boolean) => { onReanalyze(nextMeId, nextRange); setAiEnabled(nextAi); setShowSensitive(nextSensitive); setShareMode(nextMode); setAllowShare(nextShare); setSettingsOpen(false); setAi(null); setShareLink(""); };
  const content: Record<TabId, ReactNode> = { overview: <Overview report={report} onGo={goto} />, interaction: showSensitive ? <Interaction report={report} /> : <SensitiveHidden />, response: <Response report={report} />, habits: <Habits report={report} />, emotion: <EmotionTrend report={report} />, heatmap: <HeatmapV2 report={report} />, drive: <ConversationDrive report={report} />, rhythm: <Rhythm report={report} />, similarity: <Similarity report={report} />, words: <Words report={report} />, personality: <Personality report={report} />, topics: <Topics report={report} />, lifecycle: <TopicLifecycle report={report} />, conflict: showSensitive ? <Conflict report={report} /> : <SensitiveHidden />, silence: <Silence report={report} />, links: <Links report={report} />, balance: <Balance report={report} />, timeline: <Timeline report={report} />, highlights: <Highlights report={report} />, achievements: <Achievements report={report} />, recap: <Recap report={report} />, quality: <Quality report={report} />, search: <MemorySearch messages={messages} />, ai: <><AiReport report={report} ai={ai} onEnable={() => { if (aiEnabled) setAiOpen(true); else window.alert("你已在分析設定中關閉 AI 功能；如要使用，請先重新開啟設定。"); }} /><AskAi report={report} onAsk={askAi} /></> };
  const printNow = () => { setPrintOpen(false); window.setTimeout(() => window.print(), 120); };
  return <div className="flow-page"><header className="flow-header no-print"><div className="page-wrap top-nav"><Logo /><div className="nav-actions"><button className="btn-ghost" onClick={onReset} style={{ minHeight: 36, padding: "0 12px" }}><ArrowLeft size={14} />重新分析</button></div></div></header><div className="page-wrap report-layout"><Sidebar active={active} onChange={goto} /><main className="report-main"><ReportHeader report={report} currentRange={currentRange} onPrint={() => setPrintOpen(true)} onShare={() => void share()} onSettings={() => setSettingsOpen(true)} shareLink={shareLink} shareBusy={shareBusy} shareDisabled={!allowShare} shareMode={shareMode} /><section className="report-section" id={`report-${active}`}>{content[active]}</section><div className="print-book">{printSections.map((id) => <section className="report-section" key={id}>{content[id]}</section>)}</div></main></div><MobileNav active={active} onChange={goto} />{aiOpen && <ConsentModal onCancel={() => { setAiOpen(false); setAiError(""); }} onConfirm={() => void runAi()} loading={aiLoading} error={aiError} />}{askRequest && <AskConsentModal request={askRequest} onCancel={() => { askRequest.resolve("已取消這次 AI 問答，沒有傳送資料。"); setAskRequest(null); }} onConfirm={() => void confirmAsk()} loading={askLoading} error={askError} />}{settingsOpen && <SettingsModal report={report} participants={participants} currentMeId={currentMeId} currentRange={currentRange} aiEnabled={aiEnabled} showSensitive={showSensitive} shareMode={shareMode} allowShare={allowShare} onClose={() => setSettingsOpen(false)} onClear={onReset} onApply={applySettings} />}{printOpen && <PrintOptionsModal selected={printSections} onClose={() => setPrintOpen(false)} onPrint={printNow} onToggle={(id) => setPrintSections((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])} />}</div>;
}

export default function ChatAnalyzer() {
  const motionScope = useRef<HTMLDivElement>(null);
  const [step, setStep] = useState<FlowStep>("home"); const [platform, setPlatform] = useState<Platform | null>(null); const [parsed, setParsed] = useState<ParseResult | null>(null); const [report, setReport] = useState<AnalysisReport | null>(null); const [currentMeId, setCurrentMeId] = useState(""); const [currentRange, setCurrentRange] = useState<AnalysisRange>({ preset: "all" });
  const start = () => setStep("platform");
  const reset = () => { setStep("home"); setPlatform(null); setParsed(null); setReport(null); setCurrentMeId(""); setCurrentRange({ preset: "all" }); };
  useGsapMotion(motionScope, step);
  const reanalyze = (nextMeId: string, nextRange: AnalysisRange) => {
    if (!parsed || !platform) return;
    const selectedMessages = filteredByRange(parsed.messages, nextRange); const ids = new Set(selectedMessages.map((message) => message.sender_id));
    if (selectedMessages.length < 2 || ids.size < 2 || !ids.has(nextMeId)) { window.alert("這個期間內的聊天資料不足兩位聊天者，請調整日期範圍後再試。"); return; }
    setCurrentMeId(nextMeId); setCurrentRange(nextRange); setReport(analyzeChat(selectedMessages, platform, nextMeId, parsed.warnings));
  };
  if (step === "home") return <div ref={motionScope} className="motion-root"><HomePage onStart={start} /></div>;
  if (step === "platform") return <div ref={motionScope} className="motion-root"><PlatformPicker onSelect={(value) => { setPlatform(value); setStep("guide"); }} onBack={() => setStep("home")} /></div>;
  if (step === "guide" && platform) return <div ref={motionScope} className="motion-root"><Guide platform={platform} onReady={() => setStep("upload")} onBack={() => setStep("platform")} /></div>;
  if (step === "upload" && platform) return <div ref={motionScope} className="motion-root"><Upload platform={platform} onParsed={(value) => { setParsed(value); setStep("identify"); }} onBack={() => setStep("guide")} /></div>;
  if (step === "identify" && platform && parsed) return <div ref={motionScope} className="motion-root"><Identify parsed={parsed} platform={platform} onStart={(meId) => { setCurrentMeId(meId); setCurrentRange({ preset: "all" }); setReport(analyzeChat(parsed.messages, platform, meId, parsed.warnings)); setStep("report"); }} onBack={() => setStep("upload")} /></div>;
  if (step === "report" && report && parsed) return <div ref={motionScope} className="motion-root"><ReportPage report={report} messages={filteredByRange(parsed.messages, currentRange)} participants={parsed.participants} currentMeId={currentMeId} currentRange={currentRange} onReanalyze={reanalyze} onReset={reset} /></div>;
  return null;
}
