"use client";

import { useMemo, useState } from "react";
import { Activity, Award, BarChart3, BrainCircuit, CheckCircle2, Clock3, ExternalLink, Flame, Info, Link2, MessageCircle, Moon, Search, ShieldCheck, Sparkles, Timer, TrendingDown, TrendingUp, Users, Zap } from "lucide-react";
import { searchChat } from "@/lib/chat/v2";
import type { AnalysisReport, NormalizedMessage } from "@/lib/chat/types";

function SectionTitle({ title, detail }: { title: string; detail?: string }) { return <div className="report-section-title"><h3>{title}</h3>{detail && <span>{detail}</span>}</div>; }
function CardTitle({ icon: Icon, title, detail }: { icon?: typeof Info; title: string; detail?: string }) { return <div className="card-title"><h4>{Icon && <Icon size={15} style={{ verticalAlign: "middle", marginRight: 6, color: "var(--blue)" }} />}{title}</h4>{detail && <span className="status-pill">{detail}</span>}</div>; }
function EmptyState({ text }: { text: string }) { return <div className="empty-v2"><Info size={17} /><span>{text}</span></div>; }
function Confidence({ score, note, reasons }: { score: number; note: string; reasons?: string[] }) { return <div className="confidence-panel"><div><b>推測可信度 {score}%</b><span>{score >= 75 ? "高" : score >= 48 ? "中" : "低"}</span></div><p>{note}</p>{reasons && <ul>{reasons.slice(0, 3).map((reason) => <li key={reason}>{reason}</li>)}</ul>}</div>; }
function MiniBar({ label, value, maxValue, color = "#2d6cdf", detail }: { label: string; value: number; maxValue: number; color?: string; detail?: string }) { return <div className="v2-mini-bar"><div><span>{label}</span><b>{detail ?? value.toLocaleString()}</b></div><div className="bar-track"><div className="bar-fill" style={{ width: `${Math.max(value ? 3 : 0, (value / Math.max(1, maxValue)) * 100)}%`, background: color }} /></div></div>; }

export function EmotionTrend({ report }: { report: AnalysisReport }) {
  const data = report.v2.emotion.trend; const maxValue = Math.max(1, ...data.map((item) => Math.max(item.positive, item.negative, item.neutral)));
  return <><SectionTitle title="情緒趨勢時間軸" detail="可觀察文字訊號，不是情緒診斷" /><div className="surface-card card-pad"><CardTitle icon={Activity} title="正向、負向與中性互動" detail={report.v2.emotion.overall} />{data.length ? <div className="emotion-chart">{data.map((item) => <div className="emotion-column" key={item.label} title={`${item.label} · 正向 ${item.positive} · 負向 ${item.negative} · 中性 ${item.neutral}`}><div className="emotion-bars"><i className="positive" style={{ height: `${Math.max(item.positive ? 5 : 0, item.positive / maxValue * 96)}px` }} /><i className="negative" style={{ height: `${Math.max(item.negative ? 5 : 0, item.negative / maxValue * 96)}px` }} /><i className="neutral" style={{ height: `${Math.max(item.neutral ? 5 : 0, item.neutral / maxValue * 96)}px` }} /></div><small>{item.label}</small></div>)}</div> : <EmptyState text="目前沒有足夠的時間資料形成情緒趨勢。" />}<div className="legend-row"><span><i className="legend-dot positive" />正向訊號</span><span><i className="legend-dot negative" />負向訊號</span><span><i className="legend-dot neutral" />中性訊號</span></div><Confidence score={report.v2.emotion.confidence} note={report.v2.emotion.note} /></div></>;
}

export function HeatmapV2({ report }: { report: AnalysisReport }) {
  const data = report.v2.heatmap; const monthMax = Math.max(1, ...data.months.map((item) => item.value)); const dayMax = Math.max(1, ...data.daily.map((item) => item.value));
  return <><SectionTitle title="聊天熱度熱力圖" detail="每天 × 星期 × 月份 × 時段" /><div className="two-col"><div className="surface-card card-pad"><CardTitle icon={Flame} title="星期 × 時段" /><div className="heatmap-wrap"><div className="heatmap"><span /><>{Array.from({ length: 24 }, (_, hour) => <span className="heat-hour" key={hour}>{hour % 4 === 0 ? hour : ""}</span>)}</>{data.grid.map((row, weekday) => <span className="heat-row" key={weekday}><span className="heat-label">{["日", "一", "二", "三", "四", "五", "六"][weekday]}</span>{row.map((value, hour) => <span className="heat-cell" data-level={value >= 8 ? 4 : value >= 4 ? 3 : value >= 2 ? 2 : value ? 1 : 0} title={`${["週日", "週一", "週二", "週三", "週四", "週五", "週六"][weekday]} ${hour}:00 · ${value} 則`} key={`${weekday}-${hour}`} />)}</span>)}</div></div></div><div className="surface-card card-pad"><CardTitle icon={BarChart3} title="月份熱度" /><div className="distribution">{data.months.length ? data.months.slice(-8).map((item) => <MiniBar key={item.label} label={item.label} value={item.value} maxValue={monthMax} />) : <EmptyState text="還沒有月份資料。" />}</div></div></div><div className="surface-card card-pad" style={{ marginTop: 15 }}><CardTitle icon={Clock3} title="每天最密集的日期" detail="點狀記錄" />{data.daily.length ? <div className="daily-strip">{data.daily.slice(-18).map((item) => <div className="daily-item" key={item.label} title={`${item.label} · ${item.value} 則`}><i style={{ height: `${Math.max(5, item.value / dayMax * 90)}px` }} /><small>{item.label.slice(5)}</small></div>)}</div> : <EmptyState text="目前沒有每天的熱度資料。" />}</div></>;
}

export function ConversationDrive({ report }: { report: AnalysisReport }) { const drive = report.v2.drive; const componentMax = Math.max(1, ...drive.components.flatMap((item) => [item.me, item.them])); return <><SectionTitle title="聊天帶動力" detail="綜合互動行為，不是訊息競賽" /><div className="two-col"><div className="surface-card card-pad"><CardTitle icon={Zap} title="誰比較能把對話往前推？" /><div className="metric-pair"><div className="metric-box"><span>{report.me.name}</span><strong style={{ color: "var(--blue)" }}>{drive.me}%</strong></div><div className="metric-box"><span>{report.them.name}</span><strong style={{ color: "var(--mint)" }}>{drive.them}%</strong></div></div><div className="split-bar"><i style={{ width: `${drive.me}%` }} /><i style={{ width: `${drive.them}%` }} /></div><p className="muted">這個指標綜合開啟話題、提出問題、延續、重新開啟與主動分享，不能解讀成誰比較在乎。</p></div><div className="surface-card card-pad"><CardTitle icon={TrendingUp} title="行為拆解" detail="實際行為計數" /><div className="drive-components">{drive.components.map((item) => <div className="drive-component" key={item.label}><div className="distribution-label"><span>{item.label}</span><span>{item.me} / {item.them}</span></div><div className="dual-bars"><i style={{ width: `${item.me / componentMax * 100}%` }} /><i style={{ width: `${item.them / componentMax * 100}%` }} /></div><small>{item.description}</small></div>)}</div></div></div><Confidence score={drive.confidence} note="帶動力是根據可觀察互動動作的相對分布，樣本少時不宜過度解讀。" reasons={drive.basis} /></>; }

export function Rhythm({ report }: { report: AnalysisReport }) { const rhythm = report.v2.rhythm; return <><SectionTitle title="對話節奏分析" detail={rhythm.dominant} /><div className="three-col"><MetricTile label="輪流回覆切換" value={`${rhythm.turnPairs} 次`} icon={MessageCircle} /><MetricTile label="連續訊息片段" value={`${rhythm.consecutive.me + rhythm.consecutive.them} 次`} icon={Zap} /><MetricTile label="話題中斷後再出現" value={`${rhythm.recoveries} 次`} icon={Activity} /></div><div className="two-col" style={{ marginTop: 15 }}><div className="surface-card card-pad"><CardTitle icon={Timer} title="長文 / 短文互動" /><div className="metric-pair"><div className="metric-box"><span>{report.me.name} 長文</span><strong>{rhythm.longShort.meLong}</strong></div><div className="metric-box"><span>{report.them.name} 長文</span><strong>{rhythm.longShort.themLong}</strong></div><div className="metric-box"><span>{report.me.name} 短回覆</span><strong>{rhythm.longShort.meShort}</strong></div><div className="metric-box"><span>{report.them.name} 短回覆</span><strong>{rhythm.longShort.themShort}</strong></div></div></div><div className="surface-card card-pad"><CardTitle icon={Info} title="怎麼閱讀？" /><p className="muted">一問一答、連續訊息、長短文比例與中斷，描述的是訊息排列方式。短回覆不等於敷衍，完整判讀仍需上下文。</p><div className="notice" style={{ marginTop: 13 }}>共辨識 {rhythm.interruptions} 次 8 小時以上的互動間隔。</div></div></div><p className="muted" style={{ marginTop: 13 }}>{rhythm.note}</p></>; }
function RefreshIcon(props: { size?: number }) { return <Activity {...props} />; }
function MetricTile({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { return <div className="surface-card metric-tile"><Icon size={17} color="#5f8de2" /><span>{label}</span><strong>{value}</strong></div>; }

export function Similarity({ report }: { report: AnalysisReport }) { const data = report.v2.similarity; return <><SectionTitle title="語言風格相似度" detail="表達習慣的相近程度" /><div className="surface-card card-pad"><div className="similarity-head"><div><span>整體相似度</span><strong>{data.overall}<small>/100</small></strong></div><p>{data.note}</p></div><div className="similarity-grid">{data.dimensions.map((item) => <div className="similarity-row" key={item.label}><div><span>{item.label}</span><b>{item.similarity}%</b></div><div className="bar-track"><div className="bar-fill" style={{ width: `${item.similarity}%` }} /></div><small>{report.me.name} {item.me} · {report.them.name} {item.them}</small></div>)}</div>{data.sharedWords.length > 0 && <div className="shared-words"><span>共同使用詞語</span>{data.sharedWords.map((word) => <b key={word}>{word}</b>)}</div>}<Confidence score={data.confidence} note="比較平均訊息長度、Emoji、問句、語氣詞與常用詞；不代表感情、個性或關係結果。" /></div></>; }

export function TopicLifecycle({ report }: { report: AnalysisReport }) { const [selected, setSelected] = useState(report.v2.topicLifecycle[0]?.name ?? ""); const topic = report.v2.topicLifecycle.find((item) => item.name === selected); const maxValue = Math.max(1, ...(topic?.periods.map((item) => item.count) ?? [1])); return <><SectionTitle title="話題生命週期" detail="首次出現 → 活躍 → 高峰 → 最近" /><div className="surface-card card-pad"><div className="topic-tabs">{report.v2.topicLifecycle.map((item) => <button className={item.name === selected ? "active" : ""} key={item.name} onClick={() => setSelected(item.name)}>{item.name}</button>)}</div>{topic ? <div className="lifecycle-body"><div className="lifecycle-summary"><div><span>首次出現</span><b>{topic.first}</b></div><div><span>最高峰</span><b>{topic.peak}</b></div><div><span>最近出現</span><b>{topic.last}</b></div><div><span>活躍期間</span><b>{topic.activePeriods} 個月</b></div></div><div className="lifecycle-chart">{topic.periods.map((item) => <div className="bar-column" key={item.label}><i style={{ height: `${Math.max(4, item.count / maxValue * 105)}px` }} /><small>{item.label}</small></div>)}</div><p className="muted">「{topic.name}」共出現 {topic.total} 次相關詞彙訊號。這描述話題何時出現，不判斷話題對你們的意義。</p></div> : <EmptyState text="文字資料不足，暫時沒有可追蹤的話題生命週期。" />}</div></>; }

export function Silence({ report }: { report: AnalysisReport }) { const data = report.v2.silence; return <><SectionTitle title="沉默分析" detail="訊息間隔與聊天下降" /><div className="two-col"><div className="surface-card card-pad"><CardTitle icon={Moon} title="最長聊天中斷" /><div className="silence-number"><strong>{data.longest.hours ? `${data.longest.hours} 小時` : "—"}</strong><span>{data.longest.start} → {data.longest.end}</span></div><p className="muted">找出兩則訊息之間最長的時間差；沒有訊息不代表已讀、冷淡或任何人的意圖。</p></div><div className="surface-card card-pad"><CardTitle icon={TrendingDown} title="聊天突然降低" detail="月份比較" />{data.drops.length ? <div className="distribution">{data.drops.map((drop) => <MiniBar key={drop.period} label={drop.period} value={Math.abs(drop.change)} maxValue={100} color="#ef866c" detail={`下降 ${Math.abs(drop.change)}%`} />)}</div> : <EmptyState text="沒有足夠的月份訊息標記突然下降。" />}</div></div><Confidence score={data.confidence} note={data.note} /></>; }

export function Links({ report }: { report: AnalysisReport }) { const data = report.v2.links; return <><SectionTitle title="連結分析" detail="依網址類型統計" /><div className="surface-card card-pad"><CardTitle icon={Link2} title="你們分享過哪些連結？" detail={`${data.total} 個 URL`} />{data.types.length ? <div className="link-grid">{data.types.map((item) => <div className="link-type" key={item.label}><ExternalLink size={16} color="#5d88dd" /><span>{item.label}</span><strong>{item.count}</strong></div>)}</div> : <EmptyState text="這份紀錄中沒有辨識到 URL。" />}<p className="muted" style={{ marginTop: 17 }}>只保存 URL 類型與數量；原始連結仍只存在本機訊息資料中，不會因為這張統計卡上傳。</p></div></>; }

export function Balance({ report }: { report: AnalysisReport }) { const data = report.v2.balance; return <><SectionTitle title="聊天平衡度" detail="互動分布是否相對接近" /><div className="surface-card card-pad"><div className="balance-head"><div className="balance-score"><strong>{data.score}</strong><span>/ 100</span></div><div><h4>相對平衡</h4><p>它綜合訊息比例、聊天帶動、回覆參與與節奏分布，不解讀成誰比較在乎。</p></div></div><div className="balance-grid">{data.dimensions.map((item) => <MiniBar key={item.label} label={item.label} value={item.score} maxValue={100} detail={`${item.score} / 100`} />)}</div><Confidence score={data.confidence} note={data.note} /></div></>; }

export function Achievements({ report }: { report: AnalysisReport }) { const unlocked = report.v2.achievements.filter((item) => item.unlocked); return <><SectionTitle title="聊天成就" detail={`${unlocked.length} / ${report.v2.achievements.length} 已解鎖`} /><div className="achievement-grid">{report.v2.achievements.map((item) => <div className={`surface-card achievement-card ${item.unlocked ? "unlocked" : "locked"}`} key={item.id}><div className="achievement-icon">{item.unlocked ? item.icon : "○"}</div><div><h4>{item.title}</h4><span className="achievement-owner">{item.ownerName} · {item.unlocked ? "已解鎖" : "尚未解鎖"}</span><p>{item.description}</p><small>{item.value}</small></div></div>)}</div><div className="notice" style={{ marginTop: 15 }}><Award size={16} style={{ flex: "0 0 auto", color: "#c69639" }} /><span>每個成就都從這份聊天檔案的真實統計動態判定，沒有預填成就；尚未解鎖不代表任何負面評價。</span></div></>; }

export function Highlights({ report }: { report: AnalysisReport }) { const data = report.v2.highlights; return <><SectionTitle title="聊天亮點" detail="最值得回看的幾個數字" /><div className="highlight-grid"><Highlight icon="📝" label="最長訊息" value={`${data.longestMessage.length} 字`} detail={`${data.longestMessage.name} · ${data.longestMessage.date}`} /><Highlight icon="🔥" label="最密集的一天" value={data.densestDay.label} detail={`${data.densestDay.count} 則訊息`} /><Highlight icon="💬" label="最常用詞" value={data.topWord} detail="依文字詞頻" /><Highlight icon="😂" label="最常 Emoji" value={data.topEmoji} detail="依 Emoji 統計" /><Highlight icon="🌙" label="最常聊天時段" value={data.activeHour} detail="依發送時間" /><Highlight icon="⏸" label="最長沉默" value={data.longestSilence} detail="訊息時間差" /><Highlight icon="📚" label="最常話題" value={data.topTopic} detail="依詞彙聚合" /></div></>; }
function Highlight({ icon, label, value, detail }: { icon: string; label: string; value: string; detail: string }) { return <div className="surface-card highlight-card"><span>{icon}</span><small>{label}</small><strong>{value}</strong><em>{detail}</em></div>; }

export function Quality({ report }: { report: AnalysisReport }) { const data = report.v2.quality; return <><SectionTitle title="資料品質檢查" detail="分析前後都值得確認" /><div className="surface-card card-pad"><div className="quality-head"><CheckCircle2 size={22} color={data.completeness === "高" ? "var(--mint)" : "#d49b3b"} /><div><h4>整體完整度：{data.completeness}</h4><p>{data.note}</p></div></div><div className="quality-grid"><div><span>日期覆蓋率</span><strong>{data.dateCoverage}%</strong></div><div><span>未知訊息</span><strong>{data.unknownMessages} 則</strong></div><div><span>超長日期間隔</span><strong>{data.dateGaps} 段</strong></div></div>{data.warnings.length > 0 && <div className="warning-list">{data.warnings.map((warning) => <span key={warning}><Info size={13} />{warning}</span>)}</div>}<p className="muted" style={{ margin: "17px 0 0" }}>日期不連續不一定代表檔案不完整，也可能只是你們當時沒有聊天。這些檢查只用來提醒哪些推測需要保守閱讀。</p></div></>; }

export function MemorySearch({ messages }: { messages: NormalizedMessage[] }) { const [query, setQuery] = useState(""); const results = useMemo(() => searchChat(messages, query), [messages, query]); return <><SectionTitle title="聊天記憶搜尋" detail="完全在這台裝置執行" /><div className="surface-card card-pad"><div className="search-box"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋：旅行、那次考試、一起吃飯…" aria-label="搜尋聊天記憶" /><button className="btn-primary" disabled={!query.trim()} onClick={() => setQuery(query.trim())}>搜尋</button></div><p className="muted">支援關鍵字命中；找不到完全相同文字時，會用中文詞語重疊做「語意近似」排序。結果不會傳送到伺服器。</p>{query.trim() && <div className="search-results">{results.length ? results.map((item) => <div className="search-result" key={item.message.message_id}><div><span>{new Date(item.message.timestamp).toLocaleDateString("zh-TW")} · {item.message.sender_name}</span><small>{item.matchType} · 訊息位置 #{item.index}</small></div><p>{item.message.content || `［${item.message.message_type}］`}</p></div>) : <EmptyState text="沒有找到相關記憶。你可以換一個詞，或試試更具體的時間與主題。" />}</div>}</div></>; }

export function AskAi({ report, onAsk }: { report: AnalysisReport; onAsk: (question: string) => Promise<string> }) { const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [loading, setLoading] = useState(false); const suggestions = ["我們什麼時候開始常聊天？", "我們最常聊什麼？", "誰比較常主動？", "我們是不是有一段時間沒聊天？"]; const ask = async (value = question) => { if (!value.trim() || loading) return; setLoading(true); setAnswer(""); try { setAnswer(await onAsk(value.trim())); } catch (error) { setAnswer(error instanceof Error ? error.message : "目前無法回答這個問題。"); } finally { setLoading(false); } }; return <><SectionTitle title="AI 問問你的聊天" detail="先以目前資料回答" /><div className="surface-card ai-card ask-ai-card"><div className="ai-heading"><span className="ai-symbol"><BrainCircuit size={20} /></span><div><h3>問我一個關於這段聊天的問題</h3><p style={{ margin: "7px 0 0" }}>AI 只會根據目前解析出的統計、事件與搜尋結果回答；不知道的事情會直接說資料不足。</p></div></div><div className="ask-suggestions">{suggestions.map((item) => <button className="btn-ghost" key={item} onClick={() => { setQuestion(item); void ask(item); }}>{item}</button>)}</div><div className="search-box ask-input"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void ask(); }} placeholder="例如：我們哪段時間最常聊天？" /><button className="btn-primary" disabled={!question.trim() || loading} onClick={() => void ask()}>{loading ? "整理中…" : "送出"}</button></div>{answer && <div className="ai-answer"><Sparkles size={15} /><p>{answer}</p></div>}<div className="caution"><ShieldCheck size={13} style={{ verticalAlign: "middle", marginRight: 4 }} />AI 問答仍需你的主動同意；送出前會先顯示資料使用說明，不會送出原始完整聊天。</div></div></>; }
