"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Ban, CheckCircle2, Clock3, Megaphone, ShieldCheck, TriangleAlert } from "lucide-react";

const errorCodes = ["FILE-001", "FILE-002", "FILE-009", "FILE-011", "ANALYSIS-004", "AI-004", "AI-005", "AI-006", "AI-010", "SHARE-003", "SHARE-004", "SHARE-009", "SYSTEM-002", "SYSTEM-003"];

type Settings = { analysisEnabled: boolean; aiEnabled: boolean; sharingEnabled: boolean; announcement: string | null; announcementLevel: string };
export default function AdminPage() {
  const [password, setPassword] = useState(""); const [logged, setLogged] = useState(false); const [settings, setSettings] = useState<Settings | null>(null); const [announcement, setAnnouncement] = useState(""); const [selectedError, setSelectedError] = useState(errorCodes[0]); const [status, setStatus] = useState(""); const [usage, setUsage] = useState<{ eventType: string; count: number }[]>([]); const [recent, setRecent] = useState<{ eventType: string; createdAt: string }[]>([]);
  const call = async (body: Record<string, unknown>) => { const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "管理員操作失敗。"); return data; };
  const login = async () => { try { await call({ action: "login", password }); setLogged(true); await refresh(); setStatus("已登入管理員後台。"); } catch (error) { setStatus(error instanceof Error ? error.message : "登入失敗。"); } };
  const refresh = async () => { const response = await fetch("/api/admin"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "無法讀取後台資料。"); setSettings(data.settings); setAnnouncement(data.settings.announcement || ""); setUsage(data.totals); setRecent(data.recent); };
  const save = async (patch: Partial<Settings>) => { try { const data = await call({ action: "settings", ...patch }); setSettings(data.settings); setAnnouncement(data.settings.announcement || ""); setStatus("設定已更新。"); } catch (error) { setStatus(error instanceof Error ? error.message : "設定更新失敗。"); } };
  const simulate = async () => { try { await call({ action: "simulate", eventType: selectedError }); setStatus(`已啟用測試錯誤 ${selectedError}。請用一般使用者視窗測試對應流程。`); } catch (error) { setStatus(error instanceof Error ? error.message : "錯誤模擬失敗。"); } };
  useEffect(() => { void fetch("/api/admin").then((response) => { if (response.ok) { setLogged(true); return response.json(); } return null; }).then((data) => { if (data) { setSettings(data.settings); setAnnouncement(data.settings.announcement || ""); setUsage(data.totals); setRecent(data.recent); } }); }, []);
  if (!logged) return <main className="support-page"><div className="support-top"><Link className="btn-ghost" href="/"><ArrowLeft size={15} />回到首頁</Link></div><div className="support-hero"><span className="eyebrow">Private control room</span><h1>管理員後台</h1><p>請輸入管理員密碼。密碼不會放在網址裡。</p></div><div className="support-content"><div className="support-card support-form"><label>管理員密碼<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void login(); }} /></label><button className="btn-primary" onClick={() => void login()}><ShieldCheck size={15} />登入後台</button>{status && <div className="notice" role="alert">{status}</div>}</div></div></main>;
  return <main className="support-page"><div className="support-top"><Link className="btn-ghost" href="/"><ArrowLeft size={15} />回到首頁</Link><button className="btn-ghost" onClick={async () => { await call({ action: "logout" }); setLogged(false); }}>登出</button></div><div className="support-hero"><span className="eyebrow">Private control room</span><h1>服務控制中心</h1><p>只記錄匿名的功能使用時間，不保存姓名、IP、聊天內容或原始檔案。</p></div><div className="support-content"><div className="admin-grid"><section className="support-card"><h2><ShieldCheck size={18} />服務開關</h2><div className="admin-switches">{settings && <><button className={`admin-toggle ${settings.analysisEnabled ? "on" : "off"}`} onClick={() => void save({ analysisEnabled: !settings.analysisEnabled })}>{settings.analysisEnabled ? "分析服務：開啟" : "分析服務：關閉"}</button><button className={`admin-toggle ${settings.aiEnabled ? "on" : "off"}`} onClick={() => void save({ aiEnabled: !settings.aiEnabled })}>{settings.aiEnabled ? "AI 服務：開啟" : "AI 服務：關閉"}</button><button className={`admin-toggle ${settings.sharingEnabled ? "on" : "off"}`} onClick={() => void save({ sharingEnabled: !settings.sharingEnabled })}>{settings.sharingEnabled ? "分享服務：開啟" : "分享服務：關閉"}</button></>}</div></section><section className="support-card"><h2><Megaphone size={18} />公告訊息</h2><textarea className="admin-textarea" value={announcement} onChange={(event) => setAnnouncement(event.target.value)} placeholder="留白則不顯示公告" /><div className="admin-inline"><select value={settings?.announcementLevel || "info"} onChange={(event) => void save({ announcementLevel: event.target.value })}><option value="info">一般公告</option><option value="warning">警告公告</option><option value="critical">重大公告</option></select><button className="btn-primary" onClick={() => void save({ announcement })}>發布公告</button></div></section><section className="support-card"><h2><TriangleAlert size={18} />錯誤模擬</h2><p>選擇錯誤代碼後，讓一般使用者流程顯示對應的測試錯誤。</p><select className="admin-select" value={selectedError} onChange={(event) => setSelectedError(event.target.value)}>{errorCodes.map((code) => <option key={code} value={code}>{code}</option>)}</select><button className="btn-primary" onClick={() => void simulate()}>啟用測試錯誤</button><button className="btn-ghost" onClick={() => void save({ announcement: "" })}><Ban size={15} />清除公告</button></section><section className="support-card"><h2><Clock3 size={18} />使用分析時間</h2><div className="usage-total">{usage.reduce((sum, item) => sum + Number(item.count), 0)} <span>次事件</span></div><div className="usage-list">{recent.map((item, index) => <div key={`${item.createdAt}-${index}`}><span>{item.eventType}</span><time>{new Date(item.createdAt).toLocaleString("zh-TW")}</time></div>)}</div></section></div>{status && <div className="notice" role="status">{status}</div>}</div></main>;
}
